// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: kv_demo.proto

#ifndef PROTOBUF_kv_5fdemo_2eproto__INCLUDED
#define PROTOBUF_kv_5fdemo_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3005000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/map.h>  // IWYU pragma: export
#include <google/protobuf/map_entry.h>
#include <google/protobuf/map_field_inl.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace protobuf_kv_5fdemo_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[2];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
void InitDefaultsPlayerSnapshot_AttrsEntry_DoNotUseImpl();
void InitDefaultsPlayerSnapshot_AttrsEntry_DoNotUse();
void InitDefaultsPlayerSnapshotImpl();
void InitDefaultsPlayerSnapshot();
inline void InitDefaults() {
  InitDefaultsPlayerSnapshot_AttrsEntry_DoNotUse();
  InitDefaultsPlayerSnapshot();
}
}  // namespace protobuf_kv_5fdemo_2eproto
namespace kvdemo {
class PlayerSnapshot;
class PlayerSnapshotDefaultTypeInternal;
extern PlayerSnapshotDefaultTypeInternal _PlayerSnapshot_default_instance_;
class PlayerSnapshot_AttrsEntry_DoNotUse;
class PlayerSnapshot_AttrsEntry_DoNotUseDefaultTypeInternal;
extern PlayerSnapshot_AttrsEntry_DoNotUseDefaultTypeInternal _PlayerSnapshot_AttrsEntry_DoNotUse_default_instance_;
}  // namespace kvdemo
namespace kvdemo {

// ===================================================================

class PlayerSnapshot_AttrsEntry_DoNotUse : public ::google::protobuf::internal::MapEntry<PlayerSnapshot_AttrsEntry_DoNotUse, 
    ::std::string, ::google::protobuf::int32,
    ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
    ::google::protobuf::internal::WireFormatLite::TYPE_INT32,
    0 > {
public:
  typedef ::google::protobuf::internal::MapEntry<PlayerSnapshot_AttrsEntry_DoNotUse, 
    ::std::string, ::google::protobuf::int32,
    ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
    ::google::protobuf::internal::WireFormatLite::TYPE_INT32,
    0 > SuperType;
  PlayerSnapshot_AttrsEntry_DoNotUse();
  PlayerSnapshot_AttrsEntry_DoNotUse(::google::protobuf::Arena* arena);
  void MergeFrom(const PlayerSnapshot_AttrsEntry_DoNotUse& other);
  static const PlayerSnapshot_AttrsEntry_DoNotUse* internal_default_instance() { return reinterpret_cast<const PlayerSnapshot_AttrsEntry_DoNotUse*>(&_PlayerSnapshot_AttrsEntry_DoNotUse_default_instance_); }
  void MergeFrom(const ::google::protobuf::Message& other) PROTOBUF_FINAL;
  ::google::protobuf::Metadata GetMetadata() const;
};

// -------------------------------------------------------------------

class PlayerSnapshot : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:kvdemo.PlayerSnapshot) */ {
 public:
  PlayerSnapshot();
  virtual ~PlayerSnapshot();

  PlayerSnapshot(const PlayerSnapshot& from);

  inline PlayerSnapshot& operator=(const PlayerSnapshot& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  PlayerSnapshot(PlayerSnapshot&& from) noexcept
    : PlayerSnapshot() {
    *this = ::std::move(from);
  }

  inline PlayerSnapshot& operator=(PlayerSnapshot&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const PlayerSnapshot& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const PlayerSnapshot* internal_default_instance() {
    return reinterpret_cast<const PlayerSnapshot*>(
               &_PlayerSnapshot_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    1;

  void Swap(PlayerSnapshot* other);
  friend void swap(PlayerSnapshot& a, PlayerSnapshot& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline PlayerSnapshot* New() const PROTOBUF_FINAL { return New(NULL); }

  PlayerSnapshot* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const PlayerSnapshot& from);
  void MergeFrom(const PlayerSnapshot& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(PlayerSnapshot* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------


  // accessors -------------------------------------------------------

  // map<string, int32> attrs = 5;
  int attrs_size() const;
  void clear_attrs();
  static const int kAttrsFieldNumber = 5;
  const ::google::protobuf::Map< ::std::string, ::google::protobuf::int32 >&
      attrs() const;
  ::google::protobuf::Map< ::std::string, ::google::protobuf::int32 >*
      mutable_attrs();

  // string nickname = 2;
  void clear_nickname();
  static const int kNicknameFieldNumber = 2;
  const ::std::string& nickname() const;
  void set_nickname(const ::std::string& value);
  #if LANG_CXX11
  void set_nickname(::std::string&& value);
  #endif
  void set_nickname(const char* value);
  void set_nickname(const char* value, size_t size);
  ::std::string* mutable_nickname();
  ::std::string* release_nickname();
  void set_allocated_nickname(::std::string* nickname);

  // uint64 player_id = 1;
  void clear_player_id();
  static const int kPlayerIdFieldNumber = 1;
  ::google::protobuf::uint64 player_id() const;
  void set_player_id(::google::protobuf::uint64 value);

  // int64 updated_at_sec = 4;
  void clear_updated_at_sec();
  static const int kUpdatedAtSecFieldNumber = 4;
  ::google::protobuf::int64 updated_at_sec() const;
  void set_updated_at_sec(::google::protobuf::int64 value);

  // int32 level = 3;
  void clear_level();
  static const int kLevelFieldNumber = 3;
  ::google::protobuf::int32 level() const;
  void set_level(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:kvdemo.PlayerSnapshot)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::MapField<
      PlayerSnapshot_AttrsEntry_DoNotUse,
      ::std::string, ::google::protobuf::int32,
      ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
      ::google::protobuf::internal::WireFormatLite::TYPE_INT32,
      0 > attrs_;
  ::google::protobuf::internal::ArenaStringPtr nickname_;
  ::google::protobuf::uint64 player_id_;
  ::google::protobuf::int64 updated_at_sec_;
  ::google::protobuf::int32 level_;
  mutable int _cached_size_;
  friend struct ::protobuf_kv_5fdemo_2eproto::TableStruct;
  friend void ::protobuf_kv_5fdemo_2eproto::InitDefaultsPlayerSnapshotImpl();
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// PlayerSnapshot

// uint64 player_id = 1;
inline void PlayerSnapshot::clear_player_id() {
  player_id_ = GOOGLE_ULONGLONG(0);
}
inline ::google::protobuf::uint64 PlayerSnapshot::player_id() const {
  // @@protoc_insertion_point(field_get:kvdemo.PlayerSnapshot.player_id)
  return player_id_;
}
inline void PlayerSnapshot::set_player_id(::google::protobuf::uint64 value) {
  
  player_id_ = value;
  // @@protoc_insertion_point(field_set:kvdemo.PlayerSnapshot.player_id)
}

// string nickname = 2;
inline void PlayerSnapshot::clear_nickname() {
  nickname_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& PlayerSnapshot::nickname() const {
  // @@protoc_insertion_point(field_get:kvdemo.PlayerSnapshot.nickname)
  return nickname_.GetNoArena();
}
inline void PlayerSnapshot::set_nickname(const ::std::string& value) {
  
  nickname_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:kvdemo.PlayerSnapshot.nickname)
}
#if LANG_CXX11
inline void PlayerSnapshot::set_nickname(::std::string&& value) {
  
  nickname_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:kvdemo.PlayerSnapshot.nickname)
}
#endif
inline void PlayerSnapshot::set_nickname(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  nickname_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:kvdemo.PlayerSnapshot.nickname)
}
inline void PlayerSnapshot::set_nickname(const char* value, size_t size) {
  
  nickname_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:kvdemo.PlayerSnapshot.nickname)
}
inline ::std::string* PlayerSnapshot::mutable_nickname() {
  
  // @@protoc_insertion_point(field_mutable:kvdemo.PlayerSnapshot.nickname)
  return nickname_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* PlayerSnapshot::release_nickname() {
  // @@protoc_insertion_point(field_release:kvdemo.PlayerSnapshot.nickname)
  
  return nickname_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void PlayerSnapshot::set_allocated_nickname(::std::string* nickname) {
  if (nickname != NULL) {
    
  } else {
    
  }
  nickname_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), nickname);
  // @@protoc_insertion_point(field_set_allocated:kvdemo.PlayerSnapshot.nickname)
}

// int32 level = 3;
inline void PlayerSnapshot::clear_level() {
  level_ = 0;
}
inline ::google::protobuf::int32 PlayerSnapshot::level() const {
  // @@protoc_insertion_point(field_get:kvdemo.PlayerSnapshot.level)
  return level_;
}
inline void PlayerSnapshot::set_level(::google::protobuf::int32 value) {
  
  level_ = value;
  // @@protoc_insertion_point(field_set:kvdemo.PlayerSnapshot.level)
}

// int64 updated_at_sec = 4;
inline void PlayerSnapshot::clear_updated_at_sec() {
  updated_at_sec_ = GOOGLE_LONGLONG(0);
}
inline ::google::protobuf::int64 PlayerSnapshot::updated_at_sec() const {
  // @@protoc_insertion_point(field_get:kvdemo.PlayerSnapshot.updated_at_sec)
  return updated_at_sec_;
}
inline void PlayerSnapshot::set_updated_at_sec(::google::protobuf::int64 value) {
  
  updated_at_sec_ = value;
  // @@protoc_insertion_point(field_set:kvdemo.PlayerSnapshot.updated_at_sec)
}

// map<string, int32> attrs = 5;
inline int PlayerSnapshot::attrs_size() const {
  return attrs_.size();
}
inline void PlayerSnapshot::clear_attrs() {
  attrs_.Clear();
}
inline const ::google::protobuf::Map< ::std::string, ::google::protobuf::int32 >&
PlayerSnapshot::attrs() const {
  // @@protoc_insertion_point(field_map:kvdemo.PlayerSnapshot.attrs)
  return attrs_.GetMap();
}
inline ::google::protobuf::Map< ::std::string, ::google::protobuf::int32 >*
PlayerSnapshot::mutable_attrs() {
  // @@protoc_insertion_point(field_mutable_map:kvdemo.PlayerSnapshot.attrs)
  return attrs_.MutableMap();
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace kvdemo

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_kv_5fdemo_2eproto__INCLUDED
