// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: kv_demo.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_kv_5fdemo_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_kv_5fdemo_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3012000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3012004 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/map.h>  // IWYU pragma: export
#include <google/protobuf/map_entry.h>
#include <google/protobuf/map_field_inl.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_kv_5fdemo_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_kv_5fdemo_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxillaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[2]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_kv_5fdemo_2eproto;
namespace kvdemo {
class PlayerSnapshot;
class PlayerSnapshotDefaultTypeInternal;
extern PlayerSnapshotDefaultTypeInternal _PlayerSnapshot_default_instance_;
class PlayerSnapshot_AttrsEntry_DoNotUse;
class PlayerSnapshot_AttrsEntry_DoNotUseDefaultTypeInternal;
extern PlayerSnapshot_AttrsEntry_DoNotUseDefaultTypeInternal _PlayerSnapshot_AttrsEntry_DoNotUse_default_instance_;
}  // namespace kvdemo
PROTOBUF_NAMESPACE_OPEN
template<> ::kvdemo::PlayerSnapshot* Arena::CreateMaybeMessage<::kvdemo::PlayerSnapshot>(Arena*);
template<> ::kvdemo::PlayerSnapshot_AttrsEntry_DoNotUse* Arena::CreateMaybeMessage<::kvdemo::PlayerSnapshot_AttrsEntry_DoNotUse>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace kvdemo {

// ===================================================================

class PlayerSnapshot_AttrsEntry_DoNotUse : public ::PROTOBUF_NAMESPACE_ID::internal::MapEntry<PlayerSnapshot_AttrsEntry_DoNotUse, 
    std::string, ::PROTOBUF_NAMESPACE_ID::int32,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_STRING,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_INT32,
    0 > {
public:
  typedef ::PROTOBUF_NAMESPACE_ID::internal::MapEntry<PlayerSnapshot_AttrsEntry_DoNotUse, 
    std::string, ::PROTOBUF_NAMESPACE_ID::int32,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_STRING,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_INT32,
    0 > SuperType;
  PlayerSnapshot_AttrsEntry_DoNotUse();
  PlayerSnapshot_AttrsEntry_DoNotUse(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  void MergeFrom(const PlayerSnapshot_AttrsEntry_DoNotUse& other);
  static const PlayerSnapshot_AttrsEntry_DoNotUse* internal_default_instance() { return reinterpret_cast<const PlayerSnapshot_AttrsEntry_DoNotUse*>(&_PlayerSnapshot_AttrsEntry_DoNotUse_default_instance_); }
  static bool ValidateKey(std::string* s) {
    return ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(s->data(), static_cast<int>(s->size()), ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::PARSE, "kvdemo.PlayerSnapshot.AttrsEntry.key");
 }
  static bool ValidateValue(void*) { return true; }
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& other) final;
  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_kv_5fdemo_2eproto);
    return ::descriptor_table_kv_5fdemo_2eproto.file_level_metadata[0];
  }

  public:
};

// -------------------------------------------------------------------

class PlayerSnapshot PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:kvdemo.PlayerSnapshot) */ {
 public:
  inline PlayerSnapshot() : PlayerSnapshot(nullptr) {};
  virtual ~PlayerSnapshot();

  PlayerSnapshot(const PlayerSnapshot& from);
  PlayerSnapshot(PlayerSnapshot&& from) noexcept
    : PlayerSnapshot() {
    *this = ::std::move(from);
  }

  inline PlayerSnapshot& operator=(const PlayerSnapshot& from) {
    CopyFrom(from);
    return *this;
  }
  inline PlayerSnapshot& operator=(PlayerSnapshot&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const PlayerSnapshot& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const PlayerSnapshot* internal_default_instance() {
    return reinterpret_cast<const PlayerSnapshot*>(
               &_PlayerSnapshot_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(PlayerSnapshot& a, PlayerSnapshot& b) {
    a.Swap(&b);
  }
  inline void Swap(PlayerSnapshot* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(PlayerSnapshot* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline PlayerSnapshot* New() const final {
    return CreateMaybeMessage<PlayerSnapshot>(nullptr);
  }

  PlayerSnapshot* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<PlayerSnapshot>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const PlayerSnapshot& from);
  void MergeFrom(const PlayerSnapshot& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(PlayerSnapshot* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "kvdemo.PlayerSnapshot";
  }
  protected:
  explicit PlayerSnapshot(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_kv_5fdemo_2eproto);
    return ::descriptor_table_kv_5fdemo_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------


  // accessors -------------------------------------------------------

  enum : int {
    kAttrsFieldNumber = 5,
    kNicknameFieldNumber = 2,
    kPlayerIdFieldNumber = 1,
    kUpdatedAtSecFieldNumber = 4,
    kLevelFieldNumber = 3,
  };
  // map<string, int32> attrs = 5;
  int attrs_size() const;
  private:
  int _internal_attrs_size() const;
  public:
  void clear_attrs();
  private:
  const ::PROTOBUF_NAMESPACE_ID::Map< std::string, ::PROTOBUF_NAMESPACE_ID::int32 >&
      _internal_attrs() const;
  ::PROTOBUF_NAMESPACE_ID::Map< std::string, ::PROTOBUF_NAMESPACE_ID::int32 >*
      _internal_mutable_attrs();
  public:
  const ::PROTOBUF_NAMESPACE_ID::Map< std::string, ::PROTOBUF_NAMESPACE_ID::int32 >&
      attrs() const;
  ::PROTOBUF_NAMESPACE_ID::Map< std::string, ::PROTOBUF_NAMESPACE_ID::int32 >*
      mutable_attrs();

  // string nickname = 2;
  void clear_nickname();
  const std::string& nickname() const;
  void set_nickname(const std::string& value);
  void set_nickname(std::string&& value);
  void set_nickname(const char* value);
  void set_nickname(const char* value, size_t size);
  std::string* mutable_nickname();
  std::string* release_nickname();
  void set_allocated_nickname(std::string* nickname);
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  std::string* unsafe_arena_release_nickname();
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  void unsafe_arena_set_allocated_nickname(
      std::string* nickname);
  private:
  const std::string& _internal_nickname() const;
  void _internal_set_nickname(const std::string& value);
  std::string* _internal_mutable_nickname();
  public:

  // uint64 player_id = 1;
  void clear_player_id();
  ::PROTOBUF_NAMESPACE_ID::uint64 player_id() const;
  void set_player_id(::PROTOBUF_NAMESPACE_ID::uint64 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint64 _internal_player_id() const;
  void _internal_set_player_id(::PROTOBUF_NAMESPACE_ID::uint64 value);
  public:

  // int64 updated_at_sec = 4;
  void clear_updated_at_sec();
  ::PROTOBUF_NAMESPACE_ID::int64 updated_at_sec() const;
  void set_updated_at_sec(::PROTOBUF_NAMESPACE_ID::int64 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int64 _internal_updated_at_sec() const;
  void _internal_set_updated_at_sec(::PROTOBUF_NAMESPACE_ID::int64 value);
  public:

  // int32 level = 3;
  void clear_level();
  ::PROTOBUF_NAMESPACE_ID::int32 level() const;
  void set_level(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_level() const;
  void _internal_set_level(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // @@protoc_insertion_point(class_scope:kvdemo.PlayerSnapshot)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::MapField<
      PlayerSnapshot_AttrsEntry_DoNotUse,
      std::string, ::PROTOBUF_NAMESPACE_ID::int32,
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_STRING,
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_INT32,
      0 > attrs_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr nickname_;
  ::PROTOBUF_NAMESPACE_ID::uint64 player_id_;
  ::PROTOBUF_NAMESPACE_ID::int64 updated_at_sec_;
  ::PROTOBUF_NAMESPACE_ID::int32 level_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_kv_5fdemo_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// PlayerSnapshot

// uint64 player_id = 1;
inline void PlayerSnapshot::clear_player_id() {
  player_id_ = PROTOBUF_ULONGLONG(0);
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 PlayerSnapshot::_internal_player_id() const {
  return player_id_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 PlayerSnapshot::player_id() const {
  // @@protoc_insertion_point(field_get:kvdemo.PlayerSnapshot.player_id)
  return _internal_player_id();
}
inline void PlayerSnapshot::_internal_set_player_id(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  
  player_id_ = value;
}
inline void PlayerSnapshot::set_player_id(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  _internal_set_player_id(value);
  // @@protoc_insertion_point(field_set:kvdemo.PlayerSnapshot.player_id)
}

// string nickname = 2;
inline void PlayerSnapshot::clear_nickname() {
  nickname_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline const std::string& PlayerSnapshot::nickname() const {
  // @@protoc_insertion_point(field_get:kvdemo.PlayerSnapshot.nickname)
  return _internal_nickname();
}
inline void PlayerSnapshot::set_nickname(const std::string& value) {
  _internal_set_nickname(value);
  // @@protoc_insertion_point(field_set:kvdemo.PlayerSnapshot.nickname)
}
inline std::string* PlayerSnapshot::mutable_nickname() {
  // @@protoc_insertion_point(field_mutable:kvdemo.PlayerSnapshot.nickname)
  return _internal_mutable_nickname();
}
inline const std::string& PlayerSnapshot::_internal_nickname() const {
  return nickname_.Get();
}
inline void PlayerSnapshot::_internal_set_nickname(const std::string& value) {
  
  nickname_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value, GetArena());
}
inline void PlayerSnapshot::set_nickname(std::string&& value) {
  
  nickname_.Set(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:kvdemo.PlayerSnapshot.nickname)
}
inline void PlayerSnapshot::set_nickname(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  nickname_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value),
              GetArena());
  // @@protoc_insertion_point(field_set_char:kvdemo.PlayerSnapshot.nickname)
}
inline void PlayerSnapshot::set_nickname(const char* value,
    size_t size) {
  
  nickname_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:kvdemo.PlayerSnapshot.nickname)
}
inline std::string* PlayerSnapshot::_internal_mutable_nickname() {
  
  return nickname_.Mutable(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline std::string* PlayerSnapshot::release_nickname() {
  // @@protoc_insertion_point(field_release:kvdemo.PlayerSnapshot.nickname)
  return nickname_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void PlayerSnapshot::set_allocated_nickname(std::string* nickname) {
  if (nickname != nullptr) {
    
  } else {
    
  }
  nickname_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), nickname,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:kvdemo.PlayerSnapshot.nickname)
}
inline std::string* PlayerSnapshot::unsafe_arena_release_nickname() {
  // @@protoc_insertion_point(field_unsafe_arena_release:kvdemo.PlayerSnapshot.nickname)
  GOOGLE_DCHECK(GetArena() != nullptr);
  
  return nickname_.UnsafeArenaRelease(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      GetArena());
}
inline void PlayerSnapshot::unsafe_arena_set_allocated_nickname(
    std::string* nickname) {
  GOOGLE_DCHECK(GetArena() != nullptr);
  if (nickname != nullptr) {
    
  } else {
    
  }
  nickname_.UnsafeArenaSetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      nickname, GetArena());
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:kvdemo.PlayerSnapshot.nickname)
}

// int32 level = 3;
inline void PlayerSnapshot::clear_level() {
  level_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 PlayerSnapshot::_internal_level() const {
  return level_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 PlayerSnapshot::level() const {
  // @@protoc_insertion_point(field_get:kvdemo.PlayerSnapshot.level)
  return _internal_level();
}
inline void PlayerSnapshot::_internal_set_level(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  level_ = value;
}
inline void PlayerSnapshot::set_level(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_level(value);
  // @@protoc_insertion_point(field_set:kvdemo.PlayerSnapshot.level)
}

// int64 updated_at_sec = 4;
inline void PlayerSnapshot::clear_updated_at_sec() {
  updated_at_sec_ = PROTOBUF_LONGLONG(0);
}
inline ::PROTOBUF_NAMESPACE_ID::int64 PlayerSnapshot::_internal_updated_at_sec() const {
  return updated_at_sec_;
}
inline ::PROTOBUF_NAMESPACE_ID::int64 PlayerSnapshot::updated_at_sec() const {
  // @@protoc_insertion_point(field_get:kvdemo.PlayerSnapshot.updated_at_sec)
  return _internal_updated_at_sec();
}
inline void PlayerSnapshot::_internal_set_updated_at_sec(::PROTOBUF_NAMESPACE_ID::int64 value) {
  
  updated_at_sec_ = value;
}
inline void PlayerSnapshot::set_updated_at_sec(::PROTOBUF_NAMESPACE_ID::int64 value) {
  _internal_set_updated_at_sec(value);
  // @@protoc_insertion_point(field_set:kvdemo.PlayerSnapshot.updated_at_sec)
}

// map<string, int32> attrs = 5;
inline int PlayerSnapshot::_internal_attrs_size() const {
  return attrs_.size();
}
inline int PlayerSnapshot::attrs_size() const {
  return _internal_attrs_size();
}
inline void PlayerSnapshot::clear_attrs() {
  attrs_.Clear();
}
inline const ::PROTOBUF_NAMESPACE_ID::Map< std::string, ::PROTOBUF_NAMESPACE_ID::int32 >&
PlayerSnapshot::_internal_attrs() const {
  return attrs_.GetMap();
}
inline const ::PROTOBUF_NAMESPACE_ID::Map< std::string, ::PROTOBUF_NAMESPACE_ID::int32 >&
PlayerSnapshot::attrs() const {
  // @@protoc_insertion_point(field_map:kvdemo.PlayerSnapshot.attrs)
  return _internal_attrs();
}
inline ::PROTOBUF_NAMESPACE_ID::Map< std::string, ::PROTOBUF_NAMESPACE_ID::int32 >*
PlayerSnapshot::_internal_mutable_attrs() {
  return attrs_.MutableMap();
}
inline ::PROTOBUF_NAMESPACE_ID::Map< std::string, ::PROTOBUF_NAMESPACE_ID::int32 >*
PlayerSnapshot::mutable_attrs() {
  // @@protoc_insertion_point(field_mutable_map:kvdemo.PlayerSnapshot.attrs)
  return _internal_mutable_attrs();
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace kvdemo

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_kv_5fdemo_2eproto
