// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: forward.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_forward_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_forward_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3012000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3012004 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/service.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_forward_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_forward_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxillaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[3]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_forward_2eproto;
namespace fwd {
class ForwardMeta;
class ForwardMetaDefaultTypeInternal;
extern ForwardMetaDefaultTypeInternal _ForwardMeta_default_instance_;
class ForwardReq;
class ForwardReqDefaultTypeInternal;
extern ForwardReqDefaultTypeInternal _ForwardReq_default_instance_;
class ForwardRsp;
class ForwardRspDefaultTypeInternal;
extern ForwardRspDefaultTypeInternal _ForwardRsp_default_instance_;
}  // namespace fwd
PROTOBUF_NAMESPACE_OPEN
template<> ::fwd::ForwardMeta* Arena::CreateMaybeMessage<::fwd::ForwardMeta>(Arena*);
template<> ::fwd::ForwardReq* Arena::CreateMaybeMessage<::fwd::ForwardReq>(Arena*);
template<> ::fwd::ForwardRsp* Arena::CreateMaybeMessage<::fwd::ForwardRsp>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace fwd {

// ===================================================================

class ForwardMeta PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:fwd.ForwardMeta) */ {
 public:
  inline ForwardMeta() : ForwardMeta(nullptr) {};
  virtual ~ForwardMeta();

  ForwardMeta(const ForwardMeta& from);
  ForwardMeta(ForwardMeta&& from) noexcept
    : ForwardMeta() {
    *this = ::std::move(from);
  }

  inline ForwardMeta& operator=(const ForwardMeta& from) {
    CopyFrom(from);
    return *this;
  }
  inline ForwardMeta& operator=(ForwardMeta&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const ForwardMeta& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const ForwardMeta* internal_default_instance() {
    return reinterpret_cast<const ForwardMeta*>(
               &_ForwardMeta_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(ForwardMeta& a, ForwardMeta& b) {
    a.Swap(&b);
  }
  inline void Swap(ForwardMeta* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ForwardMeta* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline ForwardMeta* New() const final {
    return CreateMaybeMessage<ForwardMeta>(nullptr);
  }

  ForwardMeta* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<ForwardMeta>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const ForwardMeta& from);
  void MergeFrom(const ForwardMeta& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ForwardMeta* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "fwd.ForwardMeta";
  }
  protected:
  explicit ForwardMeta(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_forward_2eproto);
    return ::descriptor_table_forward_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kGamelogicInstanceIdFieldNumber = 8,
    kSessionIdFieldNumber = 9,
    kFenceTokenFieldNumber = 10,
    kPlayerIdFieldNumber = 1,
    kConnectionIdFieldNumber = 2,
    kRequestIdFieldNumber = 3,
    kGenerationFieldNumber = 4,
    kMapInstanceIdFieldNumber = 5,
    kOwnerEpochFieldNumber = 6,
    kRouteVersionFieldNumber = 7,
  };
  // string gamelogic_instance_id = 8;
  void clear_gamelogic_instance_id();
  const std::string& gamelogic_instance_id() const;
  void set_gamelogic_instance_id(const std::string& value);
  void set_gamelogic_instance_id(std::string&& value);
  void set_gamelogic_instance_id(const char* value);
  void set_gamelogic_instance_id(const char* value, size_t size);
  std::string* mutable_gamelogic_instance_id();
  std::string* release_gamelogic_instance_id();
  void set_allocated_gamelogic_instance_id(std::string* gamelogic_instance_id);
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  std::string* unsafe_arena_release_gamelogic_instance_id();
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  void unsafe_arena_set_allocated_gamelogic_instance_id(
      std::string* gamelogic_instance_id);
  private:
  const std::string& _internal_gamelogic_instance_id() const;
  void _internal_set_gamelogic_instance_id(const std::string& value);
  std::string* _internal_mutable_gamelogic_instance_id();
  public:

  // string session_id = 9;
  void clear_session_id();
  const std::string& session_id() const;
  void set_session_id(const std::string& value);
  void set_session_id(std::string&& value);
  void set_session_id(const char* value);
  void set_session_id(const char* value, size_t size);
  std::string* mutable_session_id();
  std::string* release_session_id();
  void set_allocated_session_id(std::string* session_id);
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  std::string* unsafe_arena_release_session_id();
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  void unsafe_arena_set_allocated_session_id(
      std::string* session_id);
  private:
  const std::string& _internal_session_id() const;
  void _internal_set_session_id(const std::string& value);
  std::string* _internal_mutable_session_id();
  public:

  // string fence_token = 10;
  void clear_fence_token();
  const std::string& fence_token() const;
  void set_fence_token(const std::string& value);
  void set_fence_token(std::string&& value);
  void set_fence_token(const char* value);
  void set_fence_token(const char* value, size_t size);
  std::string* mutable_fence_token();
  std::string* release_fence_token();
  void set_allocated_fence_token(std::string* fence_token);
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  std::string* unsafe_arena_release_fence_token();
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  void unsafe_arena_set_allocated_fence_token(
      std::string* fence_token);
  private:
  const std::string& _internal_fence_token() const;
  void _internal_set_fence_token(const std::string& value);
  std::string* _internal_mutable_fence_token();
  public:

  // uint64 player_id = 1;
  void clear_player_id();
  ::PROTOBUF_NAMESPACE_ID::uint64 player_id() const;
  void set_player_id(::PROTOBUF_NAMESPACE_ID::uint64 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint64 _internal_player_id() const;
  void _internal_set_player_id(::PROTOBUF_NAMESPACE_ID::uint64 value);
  public:

  // uint64 connection_id = 2;
  void clear_connection_id();
  ::PROTOBUF_NAMESPACE_ID::uint64 connection_id() const;
  void set_connection_id(::PROTOBUF_NAMESPACE_ID::uint64 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint64 _internal_connection_id() const;
  void _internal_set_connection_id(::PROTOBUF_NAMESPACE_ID::uint64 value);
  public:

  // uint64 request_id = 3;
  void clear_request_id();
  ::PROTOBUF_NAMESPACE_ID::uint64 request_id() const;
  void set_request_id(::PROTOBUF_NAMESPACE_ID::uint64 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint64 _internal_request_id() const;
  void _internal_set_request_id(::PROTOBUF_NAMESPACE_ID::uint64 value);
  public:

  // uint64 generation = 4;
  void clear_generation();
  ::PROTOBUF_NAMESPACE_ID::uint64 generation() const;
  void set_generation(::PROTOBUF_NAMESPACE_ID::uint64 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint64 _internal_generation() const;
  void _internal_set_generation(::PROTOBUF_NAMESPACE_ID::uint64 value);
  public:

  // uint64 map_instance_id = 5;
  void clear_map_instance_id();
  ::PROTOBUF_NAMESPACE_ID::uint64 map_instance_id() const;
  void set_map_instance_id(::PROTOBUF_NAMESPACE_ID::uint64 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint64 _internal_map_instance_id() const;
  void _internal_set_map_instance_id(::PROTOBUF_NAMESPACE_ID::uint64 value);
  public:

  // uint64 owner_epoch = 6;
  void clear_owner_epoch();
  ::PROTOBUF_NAMESPACE_ID::uint64 owner_epoch() const;
  void set_owner_epoch(::PROTOBUF_NAMESPACE_ID::uint64 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint64 _internal_owner_epoch() const;
  void _internal_set_owner_epoch(::PROTOBUF_NAMESPACE_ID::uint64 value);
  public:

  // uint64 route_version = 7;
  void clear_route_version();
  ::PROTOBUF_NAMESPACE_ID::uint64 route_version() const;
  void set_route_version(::PROTOBUF_NAMESPACE_ID::uint64 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint64 _internal_route_version() const;
  void _internal_set_route_version(::PROTOBUF_NAMESPACE_ID::uint64 value);
  public:

  // @@protoc_insertion_point(class_scope:fwd.ForwardMeta)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr gamelogic_instance_id_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr session_id_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr fence_token_;
  ::PROTOBUF_NAMESPACE_ID::uint64 player_id_;
  ::PROTOBUF_NAMESPACE_ID::uint64 connection_id_;
  ::PROTOBUF_NAMESPACE_ID::uint64 request_id_;
  ::PROTOBUF_NAMESPACE_ID::uint64 generation_;
  ::PROTOBUF_NAMESPACE_ID::uint64 map_instance_id_;
  ::PROTOBUF_NAMESPACE_ID::uint64 owner_epoch_;
  ::PROTOBUF_NAMESPACE_ID::uint64 route_version_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_forward_2eproto;
};
// -------------------------------------------------------------------

class ForwardReq PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:fwd.ForwardReq) */ {
 public:
  inline ForwardReq() : ForwardReq(nullptr) {};
  virtual ~ForwardReq();

  ForwardReq(const ForwardReq& from);
  ForwardReq(ForwardReq&& from) noexcept
    : ForwardReq() {
    *this = ::std::move(from);
  }

  inline ForwardReq& operator=(const ForwardReq& from) {
    CopyFrom(from);
    return *this;
  }
  inline ForwardReq& operator=(ForwardReq&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const ForwardReq& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const ForwardReq* internal_default_instance() {
    return reinterpret_cast<const ForwardReq*>(
               &_ForwardReq_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(ForwardReq& a, ForwardReq& b) {
    a.Swap(&b);
  }
  inline void Swap(ForwardReq* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ForwardReq* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline ForwardReq* New() const final {
    return CreateMaybeMessage<ForwardReq>(nullptr);
  }

  ForwardReq* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<ForwardReq>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const ForwardReq& from);
  void MergeFrom(const ForwardReq& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ForwardReq* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "fwd.ForwardReq";
  }
  protected:
  explicit ForwardReq(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_forward_2eproto);
    return ::descriptor_table_forward_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kRequestPayloadFieldNumber = 2,
    kMetaFieldNumber = 1,
  };
  // bytes request_payload = 2;
  void clear_request_payload();
  const std::string& request_payload() const;
  void set_request_payload(const std::string& value);
  void set_request_payload(std::string&& value);
  void set_request_payload(const char* value);
  void set_request_payload(const void* value, size_t size);
  std::string* mutable_request_payload();
  std::string* release_request_payload();
  void set_allocated_request_payload(std::string* request_payload);
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  std::string* unsafe_arena_release_request_payload();
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  void unsafe_arena_set_allocated_request_payload(
      std::string* request_payload);
  private:
  const std::string& _internal_request_payload() const;
  void _internal_set_request_payload(const std::string& value);
  std::string* _internal_mutable_request_payload();
  public:

  // .fwd.ForwardMeta meta = 1;
  bool has_meta() const;
  private:
  bool _internal_has_meta() const;
  public:
  void clear_meta();
  const ::fwd::ForwardMeta& meta() const;
  ::fwd::ForwardMeta* release_meta();
  ::fwd::ForwardMeta* mutable_meta();
  void set_allocated_meta(::fwd::ForwardMeta* meta);
  private:
  const ::fwd::ForwardMeta& _internal_meta() const;
  ::fwd::ForwardMeta* _internal_mutable_meta();
  public:
  void unsafe_arena_set_allocated_meta(
      ::fwd::ForwardMeta* meta);
  ::fwd::ForwardMeta* unsafe_arena_release_meta();

  // @@protoc_insertion_point(class_scope:fwd.ForwardReq)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr request_payload_;
  ::fwd::ForwardMeta* meta_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_forward_2eproto;
};
// -------------------------------------------------------------------

class ForwardRsp PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:fwd.ForwardRsp) */ {
 public:
  inline ForwardRsp() : ForwardRsp(nullptr) {};
  virtual ~ForwardRsp();

  ForwardRsp(const ForwardRsp& from);
  ForwardRsp(ForwardRsp&& from) noexcept
    : ForwardRsp() {
    *this = ::std::move(from);
  }

  inline ForwardRsp& operator=(const ForwardRsp& from) {
    CopyFrom(from);
    return *this;
  }
  inline ForwardRsp& operator=(ForwardRsp&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const ForwardRsp& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const ForwardRsp* internal_default_instance() {
    return reinterpret_cast<const ForwardRsp*>(
               &_ForwardRsp_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(ForwardRsp& a, ForwardRsp& b) {
    a.Swap(&b);
  }
  inline void Swap(ForwardRsp* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ForwardRsp* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline ForwardRsp* New() const final {
    return CreateMaybeMessage<ForwardRsp>(nullptr);
  }

  ForwardRsp* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<ForwardRsp>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const ForwardRsp& from);
  void MergeFrom(const ForwardRsp& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ForwardRsp* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "fwd.ForwardRsp";
  }
  protected:
  explicit ForwardRsp(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_forward_2eproto);
    return ::descriptor_table_forward_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kMessageFieldNumber = 2,
    kResponseFrameFieldNumber = 3,
    kOkFieldNumber = 1,
  };
  // string message = 2;
  void clear_message();
  const std::string& message() const;
  void set_message(const std::string& value);
  void set_message(std::string&& value);
  void set_message(const char* value);
  void set_message(const char* value, size_t size);
  std::string* mutable_message();
  std::string* release_message();
  void set_allocated_message(std::string* message);
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  std::string* unsafe_arena_release_message();
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  void unsafe_arena_set_allocated_message(
      std::string* message);
  private:
  const std::string& _internal_message() const;
  void _internal_set_message(const std::string& value);
  std::string* _internal_mutable_message();
  public:

  // bytes response_frame = 3;
  void clear_response_frame();
  const std::string& response_frame() const;
  void set_response_frame(const std::string& value);
  void set_response_frame(std::string&& value);
  void set_response_frame(const char* value);
  void set_response_frame(const void* value, size_t size);
  std::string* mutable_response_frame();
  std::string* release_response_frame();
  void set_allocated_response_frame(std::string* response_frame);
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  std::string* unsafe_arena_release_response_frame();
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  void unsafe_arena_set_allocated_response_frame(
      std::string* response_frame);
  private:
  const std::string& _internal_response_frame() const;
  void _internal_set_response_frame(const std::string& value);
  std::string* _internal_mutable_response_frame();
  public:

  // bool ok = 1;
  void clear_ok();
  bool ok() const;
  void set_ok(bool value);
  private:
  bool _internal_ok() const;
  void _internal_set_ok(bool value);
  public:

  // @@protoc_insertion_point(class_scope:fwd.ForwardRsp)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr message_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr response_frame_;
  bool ok_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_forward_2eproto;
};
// ===================================================================

class GameLogicForward_Stub;

class GameLogicForward : public ::PROTOBUF_NAMESPACE_ID::Service {
 protected:
  // This class should be treated as an abstract interface.
  inline GameLogicForward() {};
 public:
  virtual ~GameLogicForward();

  typedef GameLogicForward_Stub Stub;

  static const ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor* descriptor();

  virtual void Forward(::PROTOBUF_NAMESPACE_ID::RpcController* controller,
                       const ::fwd::ForwardReq* request,
                       ::fwd::ForwardRsp* response,
                       ::google::protobuf::Closure* done);

  // implements Service ----------------------------------------------

  const ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor* GetDescriptor();
  void CallMethod(const ::PROTOBUF_NAMESPACE_ID::MethodDescriptor* method,
                  ::PROTOBUF_NAMESPACE_ID::RpcController* controller,
                  const ::PROTOBUF_NAMESPACE_ID::Message* request,
                  ::PROTOBUF_NAMESPACE_ID::Message* response,
                  ::google::protobuf::Closure* done);
  const ::PROTOBUF_NAMESPACE_ID::Message& GetRequestPrototype(
    const ::PROTOBUF_NAMESPACE_ID::MethodDescriptor* method) const;
  const ::PROTOBUF_NAMESPACE_ID::Message& GetResponsePrototype(
    const ::PROTOBUF_NAMESPACE_ID::MethodDescriptor* method) const;

 private:
  GOOGLE_DISALLOW_EVIL_CONSTRUCTORS(GameLogicForward);
};

class GameLogicForward_Stub : public GameLogicForward {
 public:
  GameLogicForward_Stub(::PROTOBUF_NAMESPACE_ID::RpcChannel* channel);
  GameLogicForward_Stub(::PROTOBUF_NAMESPACE_ID::RpcChannel* channel,
                   ::PROTOBUF_NAMESPACE_ID::Service::ChannelOwnership ownership);
  ~GameLogicForward_Stub();

  inline ::PROTOBUF_NAMESPACE_ID::RpcChannel* channel() { return channel_; }

  // implements GameLogicForward ------------------------------------------

  void Forward(::PROTOBUF_NAMESPACE_ID::RpcController* controller,
                       const ::fwd::ForwardReq* request,
                       ::fwd::ForwardRsp* response,
                       ::google::protobuf::Closure* done);
 private:
  ::PROTOBUF_NAMESPACE_ID::RpcChannel* channel_;
  bool owns_channel_;
  GOOGLE_DISALLOW_EVIL_CONSTRUCTORS(GameLogicForward_Stub);
};


// -------------------------------------------------------------------

class WorldForward_Stub;

class WorldForward : public ::PROTOBUF_NAMESPACE_ID::Service {
 protected:
  // This class should be treated as an abstract interface.
  inline WorldForward() {};
 public:
  virtual ~WorldForward();

  typedef WorldForward_Stub Stub;

  static const ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor* descriptor();

  virtual void Forward(::PROTOBUF_NAMESPACE_ID::RpcController* controller,
                       const ::fwd::ForwardReq* request,
                       ::fwd::ForwardRsp* response,
                       ::google::protobuf::Closure* done);

  // implements Service ----------------------------------------------

  const ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor* GetDescriptor();
  void CallMethod(const ::PROTOBUF_NAMESPACE_ID::MethodDescriptor* method,
                  ::PROTOBUF_NAMESPACE_ID::RpcController* controller,
                  const ::PROTOBUF_NAMESPACE_ID::Message* request,
                  ::PROTOBUF_NAMESPACE_ID::Message* response,
                  ::google::protobuf::Closure* done);
  const ::PROTOBUF_NAMESPACE_ID::Message& GetRequestPrototype(
    const ::PROTOBUF_NAMESPACE_ID::MethodDescriptor* method) const;
  const ::PROTOBUF_NAMESPACE_ID::Message& GetResponsePrototype(
    const ::PROTOBUF_NAMESPACE_ID::MethodDescriptor* method) const;

 private:
  GOOGLE_DISALLOW_EVIL_CONSTRUCTORS(WorldForward);
};

class WorldForward_Stub : public WorldForward {
 public:
  WorldForward_Stub(::PROTOBUF_NAMESPACE_ID::RpcChannel* channel);
  WorldForward_Stub(::PROTOBUF_NAMESPACE_ID::RpcChannel* channel,
                   ::PROTOBUF_NAMESPACE_ID::Service::ChannelOwnership ownership);
  ~WorldForward_Stub();

  inline ::PROTOBUF_NAMESPACE_ID::RpcChannel* channel() { return channel_; }

  // implements WorldForward ------------------------------------------

  void Forward(::PROTOBUF_NAMESPACE_ID::RpcController* controller,
                       const ::fwd::ForwardReq* request,
                       ::fwd::ForwardRsp* response,
                       ::google::protobuf::Closure* done);
 private:
  ::PROTOBUF_NAMESPACE_ID::RpcChannel* channel_;
  bool owns_channel_;
  GOOGLE_DISALLOW_EVIL_CONSTRUCTORS(WorldForward_Stub);
};


// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// ForwardMeta

// uint64 player_id = 1;
inline void ForwardMeta::clear_player_id() {
  player_id_ = PROTOBUF_ULONGLONG(0);
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 ForwardMeta::_internal_player_id() const {
  return player_id_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 ForwardMeta::player_id() const {
  // @@protoc_insertion_point(field_get:fwd.ForwardMeta.player_id)
  return _internal_player_id();
}
inline void ForwardMeta::_internal_set_player_id(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  
  player_id_ = value;
}
inline void ForwardMeta::set_player_id(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  _internal_set_player_id(value);
  // @@protoc_insertion_point(field_set:fwd.ForwardMeta.player_id)
}

// uint64 connection_id = 2;
inline void ForwardMeta::clear_connection_id() {
  connection_id_ = PROTOBUF_ULONGLONG(0);
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 ForwardMeta::_internal_connection_id() const {
  return connection_id_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 ForwardMeta::connection_id() const {
  // @@protoc_insertion_point(field_get:fwd.ForwardMeta.connection_id)
  return _internal_connection_id();
}
inline void ForwardMeta::_internal_set_connection_id(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  
  connection_id_ = value;
}
inline void ForwardMeta::set_connection_id(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  _internal_set_connection_id(value);
  // @@protoc_insertion_point(field_set:fwd.ForwardMeta.connection_id)
}

// uint64 request_id = 3;
inline void ForwardMeta::clear_request_id() {
  request_id_ = PROTOBUF_ULONGLONG(0);
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 ForwardMeta::_internal_request_id() const {
  return request_id_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 ForwardMeta::request_id() const {
  // @@protoc_insertion_point(field_get:fwd.ForwardMeta.request_id)
  return _internal_request_id();
}
inline void ForwardMeta::_internal_set_request_id(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  
  request_id_ = value;
}
inline void ForwardMeta::set_request_id(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  _internal_set_request_id(value);
  // @@protoc_insertion_point(field_set:fwd.ForwardMeta.request_id)
}

// uint64 generation = 4;
inline void ForwardMeta::clear_generation() {
  generation_ = PROTOBUF_ULONGLONG(0);
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 ForwardMeta::_internal_generation() const {
  return generation_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 ForwardMeta::generation() const {
  // @@protoc_insertion_point(field_get:fwd.ForwardMeta.generation)
  return _internal_generation();
}
inline void ForwardMeta::_internal_set_generation(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  
  generation_ = value;
}
inline void ForwardMeta::set_generation(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  _internal_set_generation(value);
  // @@protoc_insertion_point(field_set:fwd.ForwardMeta.generation)
}

// uint64 map_instance_id = 5;
inline void ForwardMeta::clear_map_instance_id() {
  map_instance_id_ = PROTOBUF_ULONGLONG(0);
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 ForwardMeta::_internal_map_instance_id() const {
  return map_instance_id_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 ForwardMeta::map_instance_id() const {
  // @@protoc_insertion_point(field_get:fwd.ForwardMeta.map_instance_id)
  return _internal_map_instance_id();
}
inline void ForwardMeta::_internal_set_map_instance_id(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  
  map_instance_id_ = value;
}
inline void ForwardMeta::set_map_instance_id(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  _internal_set_map_instance_id(value);
  // @@protoc_insertion_point(field_set:fwd.ForwardMeta.map_instance_id)
}

// uint64 owner_epoch = 6;
inline void ForwardMeta::clear_owner_epoch() {
  owner_epoch_ = PROTOBUF_ULONGLONG(0);
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 ForwardMeta::_internal_owner_epoch() const {
  return owner_epoch_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 ForwardMeta::owner_epoch() const {
  // @@protoc_insertion_point(field_get:fwd.ForwardMeta.owner_epoch)
  return _internal_owner_epoch();
}
inline void ForwardMeta::_internal_set_owner_epoch(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  
  owner_epoch_ = value;
}
inline void ForwardMeta::set_owner_epoch(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  _internal_set_owner_epoch(value);
  // @@protoc_insertion_point(field_set:fwd.ForwardMeta.owner_epoch)
}

// uint64 route_version = 7;
inline void ForwardMeta::clear_route_version() {
  route_version_ = PROTOBUF_ULONGLONG(0);
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 ForwardMeta::_internal_route_version() const {
  return route_version_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 ForwardMeta::route_version() const {
  // @@protoc_insertion_point(field_get:fwd.ForwardMeta.route_version)
  return _internal_route_version();
}
inline void ForwardMeta::_internal_set_route_version(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  
  route_version_ = value;
}
inline void ForwardMeta::set_route_version(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  _internal_set_route_version(value);
  // @@protoc_insertion_point(field_set:fwd.ForwardMeta.route_version)
}

// string gamelogic_instance_id = 8;
inline void ForwardMeta::clear_gamelogic_instance_id() {
  gamelogic_instance_id_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline const std::string& ForwardMeta::gamelogic_instance_id() const {
  // @@protoc_insertion_point(field_get:fwd.ForwardMeta.gamelogic_instance_id)
  return _internal_gamelogic_instance_id();
}
inline void ForwardMeta::set_gamelogic_instance_id(const std::string& value) {
  _internal_set_gamelogic_instance_id(value);
  // @@protoc_insertion_point(field_set:fwd.ForwardMeta.gamelogic_instance_id)
}
inline std::string* ForwardMeta::mutable_gamelogic_instance_id() {
  // @@protoc_insertion_point(field_mutable:fwd.ForwardMeta.gamelogic_instance_id)
  return _internal_mutable_gamelogic_instance_id();
}
inline const std::string& ForwardMeta::_internal_gamelogic_instance_id() const {
  return gamelogic_instance_id_.Get();
}
inline void ForwardMeta::_internal_set_gamelogic_instance_id(const std::string& value) {
  
  gamelogic_instance_id_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value, GetArena());
}
inline void ForwardMeta::set_gamelogic_instance_id(std::string&& value) {
  
  gamelogic_instance_id_.Set(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:fwd.ForwardMeta.gamelogic_instance_id)
}
inline void ForwardMeta::set_gamelogic_instance_id(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  gamelogic_instance_id_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value),
              GetArena());
  // @@protoc_insertion_point(field_set_char:fwd.ForwardMeta.gamelogic_instance_id)
}
inline void ForwardMeta::set_gamelogic_instance_id(const char* value,
    size_t size) {
  
  gamelogic_instance_id_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:fwd.ForwardMeta.gamelogic_instance_id)
}
inline std::string* ForwardMeta::_internal_mutable_gamelogic_instance_id() {
  
  return gamelogic_instance_id_.Mutable(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline std::string* ForwardMeta::release_gamelogic_instance_id() {
  // @@protoc_insertion_point(field_release:fwd.ForwardMeta.gamelogic_instance_id)
  return gamelogic_instance_id_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void ForwardMeta::set_allocated_gamelogic_instance_id(std::string* gamelogic_instance_id) {
  if (gamelogic_instance_id != nullptr) {
    
  } else {
    
  }
  gamelogic_instance_id_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), gamelogic_instance_id,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:fwd.ForwardMeta.gamelogic_instance_id)
}
inline std::string* ForwardMeta::unsafe_arena_release_gamelogic_instance_id() {
  // @@protoc_insertion_point(field_unsafe_arena_release:fwd.ForwardMeta.gamelogic_instance_id)
  GOOGLE_DCHECK(GetArena() != nullptr);
  
  return gamelogic_instance_id_.UnsafeArenaRelease(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      GetArena());
}
inline void ForwardMeta::unsafe_arena_set_allocated_gamelogic_instance_id(
    std::string* gamelogic_instance_id) {
  GOOGLE_DCHECK(GetArena() != nullptr);
  if (gamelogic_instance_id != nullptr) {
    
  } else {
    
  }
  gamelogic_instance_id_.UnsafeArenaSetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      gamelogic_instance_id, GetArena());
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:fwd.ForwardMeta.gamelogic_instance_id)
}

// string session_id = 9;
inline void ForwardMeta::clear_session_id() {
  session_id_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline const std::string& ForwardMeta::session_id() const {
  // @@protoc_insertion_point(field_get:fwd.ForwardMeta.session_id)
  return _internal_session_id();
}
inline void ForwardMeta::set_session_id(const std::string& value) {
  _internal_set_session_id(value);
  // @@protoc_insertion_point(field_set:fwd.ForwardMeta.session_id)
}
inline std::string* ForwardMeta::mutable_session_id() {
  // @@protoc_insertion_point(field_mutable:fwd.ForwardMeta.session_id)
  return _internal_mutable_session_id();
}
inline const std::string& ForwardMeta::_internal_session_id() const {
  return session_id_.Get();
}
inline void ForwardMeta::_internal_set_session_id(const std::string& value) {
  
  session_id_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value, GetArena());
}
inline void ForwardMeta::set_session_id(std::string&& value) {
  
  session_id_.Set(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:fwd.ForwardMeta.session_id)
}
inline void ForwardMeta::set_session_id(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  session_id_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value),
              GetArena());
  // @@protoc_insertion_point(field_set_char:fwd.ForwardMeta.session_id)
}
inline void ForwardMeta::set_session_id(const char* value,
    size_t size) {
  
  session_id_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:fwd.ForwardMeta.session_id)
}
inline std::string* ForwardMeta::_internal_mutable_session_id() {
  
  return session_id_.Mutable(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline std::string* ForwardMeta::release_session_id() {
  // @@protoc_insertion_point(field_release:fwd.ForwardMeta.session_id)
  return session_id_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void ForwardMeta::set_allocated_session_id(std::string* session_id) {
  if (session_id != nullptr) {
    
  } else {
    
  }
  session_id_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), session_id,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:fwd.ForwardMeta.session_id)
}
inline std::string* ForwardMeta::unsafe_arena_release_session_id() {
  // @@protoc_insertion_point(field_unsafe_arena_release:fwd.ForwardMeta.session_id)
  GOOGLE_DCHECK(GetArena() != nullptr);
  
  return session_id_.UnsafeArenaRelease(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      GetArena());
}
inline void ForwardMeta::unsafe_arena_set_allocated_session_id(
    std::string* session_id) {
  GOOGLE_DCHECK(GetArena() != nullptr);
  if (session_id != nullptr) {
    
  } else {
    
  }
  session_id_.UnsafeArenaSetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      session_id, GetArena());
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:fwd.ForwardMeta.session_id)
}

// string fence_token = 10;
inline void ForwardMeta::clear_fence_token() {
  fence_token_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline const std::string& ForwardMeta::fence_token() const {
  // @@protoc_insertion_point(field_get:fwd.ForwardMeta.fence_token)
  return _internal_fence_token();
}
inline void ForwardMeta::set_fence_token(const std::string& value) {
  _internal_set_fence_token(value);
  // @@protoc_insertion_point(field_set:fwd.ForwardMeta.fence_token)
}
inline std::string* ForwardMeta::mutable_fence_token() {
  // @@protoc_insertion_point(field_mutable:fwd.ForwardMeta.fence_token)
  return _internal_mutable_fence_token();
}
inline const std::string& ForwardMeta::_internal_fence_token() const {
  return fence_token_.Get();
}
inline void ForwardMeta::_internal_set_fence_token(const std::string& value) {
  
  fence_token_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value, GetArena());
}
inline void ForwardMeta::set_fence_token(std::string&& value) {
  
  fence_token_.Set(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:fwd.ForwardMeta.fence_token)
}
inline void ForwardMeta::set_fence_token(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  fence_token_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value),
              GetArena());
  // @@protoc_insertion_point(field_set_char:fwd.ForwardMeta.fence_token)
}
inline void ForwardMeta::set_fence_token(const char* value,
    size_t size) {
  
  fence_token_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:fwd.ForwardMeta.fence_token)
}
inline std::string* ForwardMeta::_internal_mutable_fence_token() {
  
  return fence_token_.Mutable(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline std::string* ForwardMeta::release_fence_token() {
  // @@protoc_insertion_point(field_release:fwd.ForwardMeta.fence_token)
  return fence_token_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void ForwardMeta::set_allocated_fence_token(std::string* fence_token) {
  if (fence_token != nullptr) {
    
  } else {
    
  }
  fence_token_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), fence_token,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:fwd.ForwardMeta.fence_token)
}
inline std::string* ForwardMeta::unsafe_arena_release_fence_token() {
  // @@protoc_insertion_point(field_unsafe_arena_release:fwd.ForwardMeta.fence_token)
  GOOGLE_DCHECK(GetArena() != nullptr);
  
  return fence_token_.UnsafeArenaRelease(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      GetArena());
}
inline void ForwardMeta::unsafe_arena_set_allocated_fence_token(
    std::string* fence_token) {
  GOOGLE_DCHECK(GetArena() != nullptr);
  if (fence_token != nullptr) {
    
  } else {
    
  }
  fence_token_.UnsafeArenaSetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      fence_token, GetArena());
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:fwd.ForwardMeta.fence_token)
}

// -------------------------------------------------------------------

// ForwardReq

// .fwd.ForwardMeta meta = 1;
inline bool ForwardReq::_internal_has_meta() const {
  return this != internal_default_instance() && meta_ != nullptr;
}
inline bool ForwardReq::has_meta() const {
  return _internal_has_meta();
}
inline void ForwardReq::clear_meta() {
  if (GetArena() == nullptr && meta_ != nullptr) {
    delete meta_;
  }
  meta_ = nullptr;
}
inline const ::fwd::ForwardMeta& ForwardReq::_internal_meta() const {
  const ::fwd::ForwardMeta* p = meta_;
  return p != nullptr ? *p : *reinterpret_cast<const ::fwd::ForwardMeta*>(
      &::fwd::_ForwardMeta_default_instance_);
}
inline const ::fwd::ForwardMeta& ForwardReq::meta() const {
  // @@protoc_insertion_point(field_get:fwd.ForwardReq.meta)
  return _internal_meta();
}
inline void ForwardReq::unsafe_arena_set_allocated_meta(
    ::fwd::ForwardMeta* meta) {
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(meta_);
  }
  meta_ = meta;
  if (meta) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:fwd.ForwardReq.meta)
}
inline ::fwd::ForwardMeta* ForwardReq::release_meta() {
  auto temp = unsafe_arena_release_meta();
  if (GetArena() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
  return temp;
}
inline ::fwd::ForwardMeta* ForwardReq::unsafe_arena_release_meta() {
  // @@protoc_insertion_point(field_release:fwd.ForwardReq.meta)
  
  ::fwd::ForwardMeta* temp = meta_;
  meta_ = nullptr;
  return temp;
}
inline ::fwd::ForwardMeta* ForwardReq::_internal_mutable_meta() {
  
  if (meta_ == nullptr) {
    auto* p = CreateMaybeMessage<::fwd::ForwardMeta>(GetArena());
    meta_ = p;
  }
  return meta_;
}
inline ::fwd::ForwardMeta* ForwardReq::mutable_meta() {
  // @@protoc_insertion_point(field_mutable:fwd.ForwardReq.meta)
  return _internal_mutable_meta();
}
inline void ForwardReq::set_allocated_meta(::fwd::ForwardMeta* meta) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArena();
  if (message_arena == nullptr) {
    delete meta_;
  }
  if (meta) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      ::PROTOBUF_NAMESPACE_ID::Arena::GetArena(meta);
    if (message_arena != submessage_arena) {
      meta = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, meta, submessage_arena);
    }
    
  } else {
    
  }
  meta_ = meta;
  // @@protoc_insertion_point(field_set_allocated:fwd.ForwardReq.meta)
}

// bytes request_payload = 2;
inline void ForwardReq::clear_request_payload() {
  request_payload_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline const std::string& ForwardReq::request_payload() const {
  // @@protoc_insertion_point(field_get:fwd.ForwardReq.request_payload)
  return _internal_request_payload();
}
inline void ForwardReq::set_request_payload(const std::string& value) {
  _internal_set_request_payload(value);
  // @@protoc_insertion_point(field_set:fwd.ForwardReq.request_payload)
}
inline std::string* ForwardReq::mutable_request_payload() {
  // @@protoc_insertion_point(field_mutable:fwd.ForwardReq.request_payload)
  return _internal_mutable_request_payload();
}
inline const std::string& ForwardReq::_internal_request_payload() const {
  return request_payload_.Get();
}
inline void ForwardReq::_internal_set_request_payload(const std::string& value) {
  
  request_payload_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value, GetArena());
}
inline void ForwardReq::set_request_payload(std::string&& value) {
  
  request_payload_.Set(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:fwd.ForwardReq.request_payload)
}
inline void ForwardReq::set_request_payload(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  request_payload_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value),
              GetArena());
  // @@protoc_insertion_point(field_set_char:fwd.ForwardReq.request_payload)
}
inline void ForwardReq::set_request_payload(const void* value,
    size_t size) {
  
  request_payload_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:fwd.ForwardReq.request_payload)
}
inline std::string* ForwardReq::_internal_mutable_request_payload() {
  
  return request_payload_.Mutable(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline std::string* ForwardReq::release_request_payload() {
  // @@protoc_insertion_point(field_release:fwd.ForwardReq.request_payload)
  return request_payload_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void ForwardReq::set_allocated_request_payload(std::string* request_payload) {
  if (request_payload != nullptr) {
    
  } else {
    
  }
  request_payload_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), request_payload,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:fwd.ForwardReq.request_payload)
}
inline std::string* ForwardReq::unsafe_arena_release_request_payload() {
  // @@protoc_insertion_point(field_unsafe_arena_release:fwd.ForwardReq.request_payload)
  GOOGLE_DCHECK(GetArena() != nullptr);
  
  return request_payload_.UnsafeArenaRelease(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      GetArena());
}
inline void ForwardReq::unsafe_arena_set_allocated_request_payload(
    std::string* request_payload) {
  GOOGLE_DCHECK(GetArena() != nullptr);
  if (request_payload != nullptr) {
    
  } else {
    
  }
  request_payload_.UnsafeArenaSetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      request_payload, GetArena());
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:fwd.ForwardReq.request_payload)
}

// -------------------------------------------------------------------

// ForwardRsp

// bool ok = 1;
inline void ForwardRsp::clear_ok() {
  ok_ = false;
}
inline bool ForwardRsp::_internal_ok() const {
  return ok_;
}
inline bool ForwardRsp::ok() const {
  // @@protoc_insertion_point(field_get:fwd.ForwardRsp.ok)
  return _internal_ok();
}
inline void ForwardRsp::_internal_set_ok(bool value) {
  
  ok_ = value;
}
inline void ForwardRsp::set_ok(bool value) {
  _internal_set_ok(value);
  // @@protoc_insertion_point(field_set:fwd.ForwardRsp.ok)
}

// string message = 2;
inline void ForwardRsp::clear_message() {
  message_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline const std::string& ForwardRsp::message() const {
  // @@protoc_insertion_point(field_get:fwd.ForwardRsp.message)
  return _internal_message();
}
inline void ForwardRsp::set_message(const std::string& value) {
  _internal_set_message(value);
  // @@protoc_insertion_point(field_set:fwd.ForwardRsp.message)
}
inline std::string* ForwardRsp::mutable_message() {
  // @@protoc_insertion_point(field_mutable:fwd.ForwardRsp.message)
  return _internal_mutable_message();
}
inline const std::string& ForwardRsp::_internal_message() const {
  return message_.Get();
}
inline void ForwardRsp::_internal_set_message(const std::string& value) {
  
  message_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value, GetArena());
}
inline void ForwardRsp::set_message(std::string&& value) {
  
  message_.Set(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:fwd.ForwardRsp.message)
}
inline void ForwardRsp::set_message(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  message_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value),
              GetArena());
  // @@protoc_insertion_point(field_set_char:fwd.ForwardRsp.message)
}
inline void ForwardRsp::set_message(const char* value,
    size_t size) {
  
  message_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:fwd.ForwardRsp.message)
}
inline std::string* ForwardRsp::_internal_mutable_message() {
  
  return message_.Mutable(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline std::string* ForwardRsp::release_message() {
  // @@protoc_insertion_point(field_release:fwd.ForwardRsp.message)
  return message_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void ForwardRsp::set_allocated_message(std::string* message) {
  if (message != nullptr) {
    
  } else {
    
  }
  message_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), message,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:fwd.ForwardRsp.message)
}
inline std::string* ForwardRsp::unsafe_arena_release_message() {
  // @@protoc_insertion_point(field_unsafe_arena_release:fwd.ForwardRsp.message)
  GOOGLE_DCHECK(GetArena() != nullptr);
  
  return message_.UnsafeArenaRelease(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      GetArena());
}
inline void ForwardRsp::unsafe_arena_set_allocated_message(
    std::string* message) {
  GOOGLE_DCHECK(GetArena() != nullptr);
  if (message != nullptr) {
    
  } else {
    
  }
  message_.UnsafeArenaSetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      message, GetArena());
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:fwd.ForwardRsp.message)
}

// bytes response_frame = 3;
inline void ForwardRsp::clear_response_frame() {
  response_frame_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline const std::string& ForwardRsp::response_frame() const {
  // @@protoc_insertion_point(field_get:fwd.ForwardRsp.response_frame)
  return _internal_response_frame();
}
inline void ForwardRsp::set_response_frame(const std::string& value) {
  _internal_set_response_frame(value);
  // @@protoc_insertion_point(field_set:fwd.ForwardRsp.response_frame)
}
inline std::string* ForwardRsp::mutable_response_frame() {
  // @@protoc_insertion_point(field_mutable:fwd.ForwardRsp.response_frame)
  return _internal_mutable_response_frame();
}
inline const std::string& ForwardRsp::_internal_response_frame() const {
  return response_frame_.Get();
}
inline void ForwardRsp::_internal_set_response_frame(const std::string& value) {
  
  response_frame_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value, GetArena());
}
inline void ForwardRsp::set_response_frame(std::string&& value) {
  
  response_frame_.Set(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:fwd.ForwardRsp.response_frame)
}
inline void ForwardRsp::set_response_frame(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  response_frame_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value),
              GetArena());
  // @@protoc_insertion_point(field_set_char:fwd.ForwardRsp.response_frame)
}
inline void ForwardRsp::set_response_frame(const void* value,
    size_t size) {
  
  response_frame_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:fwd.ForwardRsp.response_frame)
}
inline std::string* ForwardRsp::_internal_mutable_response_frame() {
  
  return response_frame_.Mutable(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline std::string* ForwardRsp::release_response_frame() {
  // @@protoc_insertion_point(field_release:fwd.ForwardRsp.response_frame)
  return response_frame_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void ForwardRsp::set_allocated_response_frame(std::string* response_frame) {
  if (response_frame != nullptr) {
    
  } else {
    
  }
  response_frame_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), response_frame,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:fwd.ForwardRsp.response_frame)
}
inline std::string* ForwardRsp::unsafe_arena_release_response_frame() {
  // @@protoc_insertion_point(field_unsafe_arena_release:fwd.ForwardRsp.response_frame)
  GOOGLE_DCHECK(GetArena() != nullptr);
  
  return response_frame_.UnsafeArenaRelease(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      GetArena());
}
inline void ForwardRsp::unsafe_arena_set_allocated_response_frame(
    std::string* response_frame) {
  GOOGLE_DCHECK(GetArena() != nullptr);
  if (response_frame != nullptr) {
    
  } else {
    
  }
  response_frame_.UnsafeArenaSetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      response_frame, GetArena());
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:fwd.ForwardRsp.response_frame)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace fwd

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_forward_2eproto
