// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: forward.proto

#ifndef PROTOBUF_forward_2eproto__INCLUDED
#define PROTOBUF_forward_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3005000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/service.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace protobuf_forward_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[3];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
void InitDefaultsForwardMetaImpl();
void InitDefaultsForwardMeta();
void InitDefaultsForwardReqImpl();
void InitDefaultsForwardReq();
void InitDefaultsForwardRspImpl();
void InitDefaultsForwardRsp();
inline void InitDefaults() {
  InitDefaultsForwardMeta();
  InitDefaultsForwardReq();
  InitDefaultsForwardRsp();
}
}  // namespace protobuf_forward_2eproto
namespace fwd {
class ForwardMeta;
class ForwardMetaDefaultTypeInternal;
extern ForwardMetaDefaultTypeInternal _ForwardMeta_default_instance_;
class ForwardReq;
class ForwardReqDefaultTypeInternal;
extern ForwardReqDefaultTypeInternal _ForwardReq_default_instance_;
class ForwardRsp;
class ForwardRspDefaultTypeInternal;
extern ForwardRspDefaultTypeInternal _ForwardRsp_default_instance_;
}  // namespace fwd
namespace fwd {

// ===================================================================

class ForwardMeta : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:fwd.ForwardMeta) */ {
 public:
  ForwardMeta();
  virtual ~ForwardMeta();

  ForwardMeta(const ForwardMeta& from);

  inline ForwardMeta& operator=(const ForwardMeta& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  ForwardMeta(ForwardMeta&& from) noexcept
    : ForwardMeta() {
    *this = ::std::move(from);
  }

  inline ForwardMeta& operator=(ForwardMeta&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const ForwardMeta& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const ForwardMeta* internal_default_instance() {
    return reinterpret_cast<const ForwardMeta*>(
               &_ForwardMeta_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    0;

  void Swap(ForwardMeta* other);
  friend void swap(ForwardMeta& a, ForwardMeta& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline ForwardMeta* New() const PROTOBUF_FINAL { return New(NULL); }

  ForwardMeta* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const ForwardMeta& from);
  void MergeFrom(const ForwardMeta& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(ForwardMeta* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // string gamelogic_instance_id = 8;
  void clear_gamelogic_instance_id();
  static const int kGamelogicInstanceIdFieldNumber = 8;
  const ::std::string& gamelogic_instance_id() const;
  void set_gamelogic_instance_id(const ::std::string& value);
  #if LANG_CXX11
  void set_gamelogic_instance_id(::std::string&& value);
  #endif
  void set_gamelogic_instance_id(const char* value);
  void set_gamelogic_instance_id(const char* value, size_t size);
  ::std::string* mutable_gamelogic_instance_id();
  ::std::string* release_gamelogic_instance_id();
  void set_allocated_gamelogic_instance_id(::std::string* gamelogic_instance_id);

  // string session_id = 9;
  void clear_session_id();
  static const int kSessionIdFieldNumber = 9;
  const ::std::string& session_id() const;
  void set_session_id(const ::std::string& value);
  #if LANG_CXX11
  void set_session_id(::std::string&& value);
  #endif
  void set_session_id(const char* value);
  void set_session_id(const char* value, size_t size);
  ::std::string* mutable_session_id();
  ::std::string* release_session_id();
  void set_allocated_session_id(::std::string* session_id);

  // string fence_token = 10;
  void clear_fence_token();
  static const int kFenceTokenFieldNumber = 10;
  const ::std::string& fence_token() const;
  void set_fence_token(const ::std::string& value);
  #if LANG_CXX11
  void set_fence_token(::std::string&& value);
  #endif
  void set_fence_token(const char* value);
  void set_fence_token(const char* value, size_t size);
  ::std::string* mutable_fence_token();
  ::std::string* release_fence_token();
  void set_allocated_fence_token(::std::string* fence_token);

  // uint64 player_id = 1;
  void clear_player_id();
  static const int kPlayerIdFieldNumber = 1;
  ::google::protobuf::uint64 player_id() const;
  void set_player_id(::google::protobuf::uint64 value);

  // uint64 connection_id = 2;
  void clear_connection_id();
  static const int kConnectionIdFieldNumber = 2;
  ::google::protobuf::uint64 connection_id() const;
  void set_connection_id(::google::protobuf::uint64 value);

  // uint64 request_id = 3;
  void clear_request_id();
  static const int kRequestIdFieldNumber = 3;
  ::google::protobuf::uint64 request_id() const;
  void set_request_id(::google::protobuf::uint64 value);

  // uint64 generation = 4;
  void clear_generation();
  static const int kGenerationFieldNumber = 4;
  ::google::protobuf::uint64 generation() const;
  void set_generation(::google::protobuf::uint64 value);

  // uint64 map_instance_id = 5;
  void clear_map_instance_id();
  static const int kMapInstanceIdFieldNumber = 5;
  ::google::protobuf::uint64 map_instance_id() const;
  void set_map_instance_id(::google::protobuf::uint64 value);

  // uint64 owner_epoch = 6;
  void clear_owner_epoch();
  static const int kOwnerEpochFieldNumber = 6;
  ::google::protobuf::uint64 owner_epoch() const;
  void set_owner_epoch(::google::protobuf::uint64 value);

  // uint64 route_version = 7;
  void clear_route_version();
  static const int kRouteVersionFieldNumber = 7;
  ::google::protobuf::uint64 route_version() const;
  void set_route_version(::google::protobuf::uint64 value);

  // @@protoc_insertion_point(class_scope:fwd.ForwardMeta)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr gamelogic_instance_id_;
  ::google::protobuf::internal::ArenaStringPtr session_id_;
  ::google::protobuf::internal::ArenaStringPtr fence_token_;
  ::google::protobuf::uint64 player_id_;
  ::google::protobuf::uint64 connection_id_;
  ::google::protobuf::uint64 request_id_;
  ::google::protobuf::uint64 generation_;
  ::google::protobuf::uint64 map_instance_id_;
  ::google::protobuf::uint64 owner_epoch_;
  ::google::protobuf::uint64 route_version_;
  mutable int _cached_size_;
  friend struct ::protobuf_forward_2eproto::TableStruct;
  friend void ::protobuf_forward_2eproto::InitDefaultsForwardMetaImpl();
};
// -------------------------------------------------------------------

class ForwardReq : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:fwd.ForwardReq) */ {
 public:
  ForwardReq();
  virtual ~ForwardReq();

  ForwardReq(const ForwardReq& from);

  inline ForwardReq& operator=(const ForwardReq& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  ForwardReq(ForwardReq&& from) noexcept
    : ForwardReq() {
    *this = ::std::move(from);
  }

  inline ForwardReq& operator=(ForwardReq&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const ForwardReq& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const ForwardReq* internal_default_instance() {
    return reinterpret_cast<const ForwardReq*>(
               &_ForwardReq_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    1;

  void Swap(ForwardReq* other);
  friend void swap(ForwardReq& a, ForwardReq& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline ForwardReq* New() const PROTOBUF_FINAL { return New(NULL); }

  ForwardReq* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const ForwardReq& from);
  void MergeFrom(const ForwardReq& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(ForwardReq* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // bytes request_payload = 2;
  void clear_request_payload();
  static const int kRequestPayloadFieldNumber = 2;
  const ::std::string& request_payload() const;
  void set_request_payload(const ::std::string& value);
  #if LANG_CXX11
  void set_request_payload(::std::string&& value);
  #endif
  void set_request_payload(const char* value);
  void set_request_payload(const void* value, size_t size);
  ::std::string* mutable_request_payload();
  ::std::string* release_request_payload();
  void set_allocated_request_payload(::std::string* request_payload);

  // .fwd.ForwardMeta meta = 1;
  bool has_meta() const;
  void clear_meta();
  static const int kMetaFieldNumber = 1;
  const ::fwd::ForwardMeta& meta() const;
  ::fwd::ForwardMeta* release_meta();
  ::fwd::ForwardMeta* mutable_meta();
  void set_allocated_meta(::fwd::ForwardMeta* meta);

  // @@protoc_insertion_point(class_scope:fwd.ForwardReq)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr request_payload_;
  ::fwd::ForwardMeta* meta_;
  mutable int _cached_size_;
  friend struct ::protobuf_forward_2eproto::TableStruct;
  friend void ::protobuf_forward_2eproto::InitDefaultsForwardReqImpl();
};
// -------------------------------------------------------------------

class ForwardRsp : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:fwd.ForwardRsp) */ {
 public:
  ForwardRsp();
  virtual ~ForwardRsp();

  ForwardRsp(const ForwardRsp& from);

  inline ForwardRsp& operator=(const ForwardRsp& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  ForwardRsp(ForwardRsp&& from) noexcept
    : ForwardRsp() {
    *this = ::std::move(from);
  }

  inline ForwardRsp& operator=(ForwardRsp&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const ForwardRsp& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const ForwardRsp* internal_default_instance() {
    return reinterpret_cast<const ForwardRsp*>(
               &_ForwardRsp_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    2;

  void Swap(ForwardRsp* other);
  friend void swap(ForwardRsp& a, ForwardRsp& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline ForwardRsp* New() const PROTOBUF_FINAL { return New(NULL); }

  ForwardRsp* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const ForwardRsp& from);
  void MergeFrom(const ForwardRsp& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(ForwardRsp* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // string message = 2;
  void clear_message();
  static const int kMessageFieldNumber = 2;
  const ::std::string& message() const;
  void set_message(const ::std::string& value);
  #if LANG_CXX11
  void set_message(::std::string&& value);
  #endif
  void set_message(const char* value);
  void set_message(const char* value, size_t size);
  ::std::string* mutable_message();
  ::std::string* release_message();
  void set_allocated_message(::std::string* message);

  // bytes response_frame = 3;
  void clear_response_frame();
  static const int kResponseFrameFieldNumber = 3;
  const ::std::string& response_frame() const;
  void set_response_frame(const ::std::string& value);
  #if LANG_CXX11
  void set_response_frame(::std::string&& value);
  #endif
  void set_response_frame(const char* value);
  void set_response_frame(const void* value, size_t size);
  ::std::string* mutable_response_frame();
  ::std::string* release_response_frame();
  void set_allocated_response_frame(::std::string* response_frame);

  // bool ok = 1;
  void clear_ok();
  static const int kOkFieldNumber = 1;
  bool ok() const;
  void set_ok(bool value);

  // @@protoc_insertion_point(class_scope:fwd.ForwardRsp)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr message_;
  ::google::protobuf::internal::ArenaStringPtr response_frame_;
  bool ok_;
  mutable int _cached_size_;
  friend struct ::protobuf_forward_2eproto::TableStruct;
  friend void ::protobuf_forward_2eproto::InitDefaultsForwardRspImpl();
};
// ===================================================================

class GameLogicForward_Stub;

class GameLogicForward : public ::google::protobuf::Service {
 protected:
  // This class should be treated as an abstract interface.
  inline GameLogicForward() {};
 public:
  virtual ~GameLogicForward();

  typedef GameLogicForward_Stub Stub;

  static const ::google::protobuf::ServiceDescriptor* descriptor();

  virtual void Forward(::google::protobuf::RpcController* controller,
                       const ::fwd::ForwardReq* request,
                       ::fwd::ForwardRsp* response,
                       ::google::protobuf::Closure* done);

  // implements Service ----------------------------------------------

  const ::google::protobuf::ServiceDescriptor* GetDescriptor();
  void CallMethod(const ::google::protobuf::MethodDescriptor* method,
                  ::google::protobuf::RpcController* controller,
                  const ::google::protobuf::Message* request,
                  ::google::protobuf::Message* response,
                  ::google::protobuf::Closure* done);
  const ::google::protobuf::Message& GetRequestPrototype(
    const ::google::protobuf::MethodDescriptor* method) const;
  const ::google::protobuf::Message& GetResponsePrototype(
    const ::google::protobuf::MethodDescriptor* method) const;

 private:
  GOOGLE_DISALLOW_EVIL_CONSTRUCTORS(GameLogicForward);
};

class GameLogicForward_Stub : public GameLogicForward {
 public:
  GameLogicForward_Stub(::google::protobuf::RpcChannel* channel);
  GameLogicForward_Stub(::google::protobuf::RpcChannel* channel,
                   ::google::protobuf::Service::ChannelOwnership ownership);
  ~GameLogicForward_Stub();

  inline ::google::protobuf::RpcChannel* channel() { return channel_; }

  // implements GameLogicForward ------------------------------------------

  void Forward(::google::protobuf::RpcController* controller,
                       const ::fwd::ForwardReq* request,
                       ::fwd::ForwardRsp* response,
                       ::google::protobuf::Closure* done);
 private:
  ::google::protobuf::RpcChannel* channel_;
  bool owns_channel_;
  GOOGLE_DISALLOW_EVIL_CONSTRUCTORS(GameLogicForward_Stub);
};


// -------------------------------------------------------------------

class WorldForward_Stub;

class WorldForward : public ::google::protobuf::Service {
 protected:
  // This class should be treated as an abstract interface.
  inline WorldForward() {};
 public:
  virtual ~WorldForward();

  typedef WorldForward_Stub Stub;

  static const ::google::protobuf::ServiceDescriptor* descriptor();

  virtual void Forward(::google::protobuf::RpcController* controller,
                       const ::fwd::ForwardReq* request,
                       ::fwd::ForwardRsp* response,
                       ::google::protobuf::Closure* done);

  // implements Service ----------------------------------------------

  const ::google::protobuf::ServiceDescriptor* GetDescriptor();
  void CallMethod(const ::google::protobuf::MethodDescriptor* method,
                  ::google::protobuf::RpcController* controller,
                  const ::google::protobuf::Message* request,
                  ::google::protobuf::Message* response,
                  ::google::protobuf::Closure* done);
  const ::google::protobuf::Message& GetRequestPrototype(
    const ::google::protobuf::MethodDescriptor* method) const;
  const ::google::protobuf::Message& GetResponsePrototype(
    const ::google::protobuf::MethodDescriptor* method) const;

 private:
  GOOGLE_DISALLOW_EVIL_CONSTRUCTORS(WorldForward);
};

class WorldForward_Stub : public WorldForward {
 public:
  WorldForward_Stub(::google::protobuf::RpcChannel* channel);
  WorldForward_Stub(::google::protobuf::RpcChannel* channel,
                   ::google::protobuf::Service::ChannelOwnership ownership);
  ~WorldForward_Stub();

  inline ::google::protobuf::RpcChannel* channel() { return channel_; }

  // implements WorldForward ------------------------------------------

  void Forward(::google::protobuf::RpcController* controller,
                       const ::fwd::ForwardReq* request,
                       ::fwd::ForwardRsp* response,
                       ::google::protobuf::Closure* done);
 private:
  ::google::protobuf::RpcChannel* channel_;
  bool owns_channel_;
  GOOGLE_DISALLOW_EVIL_CONSTRUCTORS(WorldForward_Stub);
};


// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// ForwardMeta

// uint64 player_id = 1;
inline void ForwardMeta::clear_player_id() {
  player_id_ = GOOGLE_ULONGLONG(0);
}
inline ::google::protobuf::uint64 ForwardMeta::player_id() const {
  // @@protoc_insertion_point(field_get:fwd.ForwardMeta.player_id)
  return player_id_;
}
inline void ForwardMeta::set_player_id(::google::protobuf::uint64 value) {
  
  player_id_ = value;
  // @@protoc_insertion_point(field_set:fwd.ForwardMeta.player_id)
}

// uint64 connection_id = 2;
inline void ForwardMeta::clear_connection_id() {
  connection_id_ = GOOGLE_ULONGLONG(0);
}
inline ::google::protobuf::uint64 ForwardMeta::connection_id() const {
  // @@protoc_insertion_point(field_get:fwd.ForwardMeta.connection_id)
  return connection_id_;
}
inline void ForwardMeta::set_connection_id(::google::protobuf::uint64 value) {
  
  connection_id_ = value;
  // @@protoc_insertion_point(field_set:fwd.ForwardMeta.connection_id)
}

// uint64 request_id = 3;
inline void ForwardMeta::clear_request_id() {
  request_id_ = GOOGLE_ULONGLONG(0);
}
inline ::google::protobuf::uint64 ForwardMeta::request_id() const {
  // @@protoc_insertion_point(field_get:fwd.ForwardMeta.request_id)
  return request_id_;
}
inline void ForwardMeta::set_request_id(::google::protobuf::uint64 value) {
  
  request_id_ = value;
  // @@protoc_insertion_point(field_set:fwd.ForwardMeta.request_id)
}

// uint64 generation = 4;
inline void ForwardMeta::clear_generation() {
  generation_ = GOOGLE_ULONGLONG(0);
}
inline ::google::protobuf::uint64 ForwardMeta::generation() const {
  // @@protoc_insertion_point(field_get:fwd.ForwardMeta.generation)
  return generation_;
}
inline void ForwardMeta::set_generation(::google::protobuf::uint64 value) {
  
  generation_ = value;
  // @@protoc_insertion_point(field_set:fwd.ForwardMeta.generation)
}

// uint64 map_instance_id = 5;
inline void ForwardMeta::clear_map_instance_id() {
  map_instance_id_ = GOOGLE_ULONGLONG(0);
}
inline ::google::protobuf::uint64 ForwardMeta::map_instance_id() const {
  // @@protoc_insertion_point(field_get:fwd.ForwardMeta.map_instance_id)
  return map_instance_id_;
}
inline void ForwardMeta::set_map_instance_id(::google::protobuf::uint64 value) {
  
  map_instance_id_ = value;
  // @@protoc_insertion_point(field_set:fwd.ForwardMeta.map_instance_id)
}

// uint64 owner_epoch = 6;
inline void ForwardMeta::clear_owner_epoch() {
  owner_epoch_ = GOOGLE_ULONGLONG(0);
}
inline ::google::protobuf::uint64 ForwardMeta::owner_epoch() const {
  // @@protoc_insertion_point(field_get:fwd.ForwardMeta.owner_epoch)
  return owner_epoch_;
}
inline void ForwardMeta::set_owner_epoch(::google::protobuf::uint64 value) {
  
  owner_epoch_ = value;
  // @@protoc_insertion_point(field_set:fwd.ForwardMeta.owner_epoch)
}

// uint64 route_version = 7;
inline void ForwardMeta::clear_route_version() {
  route_version_ = GOOGLE_ULONGLONG(0);
}
inline ::google::protobuf::uint64 ForwardMeta::route_version() const {
  // @@protoc_insertion_point(field_get:fwd.ForwardMeta.route_version)
  return route_version_;
}
inline void ForwardMeta::set_route_version(::google::protobuf::uint64 value) {
  
  route_version_ = value;
  // @@protoc_insertion_point(field_set:fwd.ForwardMeta.route_version)
}

// string gamelogic_instance_id = 8;
inline void ForwardMeta::clear_gamelogic_instance_id() {
  gamelogic_instance_id_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& ForwardMeta::gamelogic_instance_id() const {
  // @@protoc_insertion_point(field_get:fwd.ForwardMeta.gamelogic_instance_id)
  return gamelogic_instance_id_.GetNoArena();
}
inline void ForwardMeta::set_gamelogic_instance_id(const ::std::string& value) {
  
  gamelogic_instance_id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:fwd.ForwardMeta.gamelogic_instance_id)
}
#if LANG_CXX11
inline void ForwardMeta::set_gamelogic_instance_id(::std::string&& value) {
  
  gamelogic_instance_id_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:fwd.ForwardMeta.gamelogic_instance_id)
}
#endif
inline void ForwardMeta::set_gamelogic_instance_id(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  gamelogic_instance_id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:fwd.ForwardMeta.gamelogic_instance_id)
}
inline void ForwardMeta::set_gamelogic_instance_id(const char* value, size_t size) {
  
  gamelogic_instance_id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:fwd.ForwardMeta.gamelogic_instance_id)
}
inline ::std::string* ForwardMeta::mutable_gamelogic_instance_id() {
  
  // @@protoc_insertion_point(field_mutable:fwd.ForwardMeta.gamelogic_instance_id)
  return gamelogic_instance_id_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* ForwardMeta::release_gamelogic_instance_id() {
  // @@protoc_insertion_point(field_release:fwd.ForwardMeta.gamelogic_instance_id)
  
  return gamelogic_instance_id_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void ForwardMeta::set_allocated_gamelogic_instance_id(::std::string* gamelogic_instance_id) {
  if (gamelogic_instance_id != NULL) {
    
  } else {
    
  }
  gamelogic_instance_id_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), gamelogic_instance_id);
  // @@protoc_insertion_point(field_set_allocated:fwd.ForwardMeta.gamelogic_instance_id)
}

// string session_id = 9;
inline void ForwardMeta::clear_session_id() {
  session_id_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& ForwardMeta::session_id() const {
  // @@protoc_insertion_point(field_get:fwd.ForwardMeta.session_id)
  return session_id_.GetNoArena();
}
inline void ForwardMeta::set_session_id(const ::std::string& value) {
  
  session_id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:fwd.ForwardMeta.session_id)
}
#if LANG_CXX11
inline void ForwardMeta::set_session_id(::std::string&& value) {
  
  session_id_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:fwd.ForwardMeta.session_id)
}
#endif
inline void ForwardMeta::set_session_id(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  session_id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:fwd.ForwardMeta.session_id)
}
inline void ForwardMeta::set_session_id(const char* value, size_t size) {
  
  session_id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:fwd.ForwardMeta.session_id)
}
inline ::std::string* ForwardMeta::mutable_session_id() {
  
  // @@protoc_insertion_point(field_mutable:fwd.ForwardMeta.session_id)
  return session_id_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* ForwardMeta::release_session_id() {
  // @@protoc_insertion_point(field_release:fwd.ForwardMeta.session_id)
  
  return session_id_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void ForwardMeta::set_allocated_session_id(::std::string* session_id) {
  if (session_id != NULL) {
    
  } else {
    
  }
  session_id_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), session_id);
  // @@protoc_insertion_point(field_set_allocated:fwd.ForwardMeta.session_id)
}

// string fence_token = 10;
inline void ForwardMeta::clear_fence_token() {
  fence_token_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& ForwardMeta::fence_token() const {
  // @@protoc_insertion_point(field_get:fwd.ForwardMeta.fence_token)
  return fence_token_.GetNoArena();
}
inline void ForwardMeta::set_fence_token(const ::std::string& value) {
  
  fence_token_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:fwd.ForwardMeta.fence_token)
}
#if LANG_CXX11
inline void ForwardMeta::set_fence_token(::std::string&& value) {
  
  fence_token_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:fwd.ForwardMeta.fence_token)
}
#endif
inline void ForwardMeta::set_fence_token(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  fence_token_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:fwd.ForwardMeta.fence_token)
}
inline void ForwardMeta::set_fence_token(const char* value, size_t size) {
  
  fence_token_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:fwd.ForwardMeta.fence_token)
}
inline ::std::string* ForwardMeta::mutable_fence_token() {
  
  // @@protoc_insertion_point(field_mutable:fwd.ForwardMeta.fence_token)
  return fence_token_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* ForwardMeta::release_fence_token() {
  // @@protoc_insertion_point(field_release:fwd.ForwardMeta.fence_token)
  
  return fence_token_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void ForwardMeta::set_allocated_fence_token(::std::string* fence_token) {
  if (fence_token != NULL) {
    
  } else {
    
  }
  fence_token_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), fence_token);
  // @@protoc_insertion_point(field_set_allocated:fwd.ForwardMeta.fence_token)
}

// -------------------------------------------------------------------

// ForwardReq

// .fwd.ForwardMeta meta = 1;
inline bool ForwardReq::has_meta() const {
  return this != internal_default_instance() && meta_ != NULL;
}
inline void ForwardReq::clear_meta() {
  if (GetArenaNoVirtual() == NULL && meta_ != NULL) {
    delete meta_;
  }
  meta_ = NULL;
}
inline const ::fwd::ForwardMeta& ForwardReq::meta() const {
  const ::fwd::ForwardMeta* p = meta_;
  // @@protoc_insertion_point(field_get:fwd.ForwardReq.meta)
  return p != NULL ? *p : *reinterpret_cast<const ::fwd::ForwardMeta*>(
      &::fwd::_ForwardMeta_default_instance_);
}
inline ::fwd::ForwardMeta* ForwardReq::release_meta() {
  // @@protoc_insertion_point(field_release:fwd.ForwardReq.meta)
  
  ::fwd::ForwardMeta* temp = meta_;
  meta_ = NULL;
  return temp;
}
inline ::fwd::ForwardMeta* ForwardReq::mutable_meta() {
  
  if (meta_ == NULL) {
    meta_ = new ::fwd::ForwardMeta;
  }
  // @@protoc_insertion_point(field_mutable:fwd.ForwardReq.meta)
  return meta_;
}
inline void ForwardReq::set_allocated_meta(::fwd::ForwardMeta* meta) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete meta_;
  }
  if (meta) {
    ::google::protobuf::Arena* submessage_arena = NULL;
    if (message_arena != submessage_arena) {
      meta = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, meta, submessage_arena);
    }
    
  } else {
    
  }
  meta_ = meta;
  // @@protoc_insertion_point(field_set_allocated:fwd.ForwardReq.meta)
}

// bytes request_payload = 2;
inline void ForwardReq::clear_request_payload() {
  request_payload_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& ForwardReq::request_payload() const {
  // @@protoc_insertion_point(field_get:fwd.ForwardReq.request_payload)
  return request_payload_.GetNoArena();
}
inline void ForwardReq::set_request_payload(const ::std::string& value) {
  
  request_payload_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:fwd.ForwardReq.request_payload)
}
#if LANG_CXX11
inline void ForwardReq::set_request_payload(::std::string&& value) {
  
  request_payload_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:fwd.ForwardReq.request_payload)
}
#endif
inline void ForwardReq::set_request_payload(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  request_payload_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:fwd.ForwardReq.request_payload)
}
inline void ForwardReq::set_request_payload(const void* value, size_t size) {
  
  request_payload_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:fwd.ForwardReq.request_payload)
}
inline ::std::string* ForwardReq::mutable_request_payload() {
  
  // @@protoc_insertion_point(field_mutable:fwd.ForwardReq.request_payload)
  return request_payload_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* ForwardReq::release_request_payload() {
  // @@protoc_insertion_point(field_release:fwd.ForwardReq.request_payload)
  
  return request_payload_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void ForwardReq::set_allocated_request_payload(::std::string* request_payload) {
  if (request_payload != NULL) {
    
  } else {
    
  }
  request_payload_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), request_payload);
  // @@protoc_insertion_point(field_set_allocated:fwd.ForwardReq.request_payload)
}

// -------------------------------------------------------------------

// ForwardRsp

// bool ok = 1;
inline void ForwardRsp::clear_ok() {
  ok_ = false;
}
inline bool ForwardRsp::ok() const {
  // @@protoc_insertion_point(field_get:fwd.ForwardRsp.ok)
  return ok_;
}
inline void ForwardRsp::set_ok(bool value) {
  
  ok_ = value;
  // @@protoc_insertion_point(field_set:fwd.ForwardRsp.ok)
}

// string message = 2;
inline void ForwardRsp::clear_message() {
  message_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& ForwardRsp::message() const {
  // @@protoc_insertion_point(field_get:fwd.ForwardRsp.message)
  return message_.GetNoArena();
}
inline void ForwardRsp::set_message(const ::std::string& value) {
  
  message_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:fwd.ForwardRsp.message)
}
#if LANG_CXX11
inline void ForwardRsp::set_message(::std::string&& value) {
  
  message_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:fwd.ForwardRsp.message)
}
#endif
inline void ForwardRsp::set_message(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  message_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:fwd.ForwardRsp.message)
}
inline void ForwardRsp::set_message(const char* value, size_t size) {
  
  message_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:fwd.ForwardRsp.message)
}
inline ::std::string* ForwardRsp::mutable_message() {
  
  // @@protoc_insertion_point(field_mutable:fwd.ForwardRsp.message)
  return message_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* ForwardRsp::release_message() {
  // @@protoc_insertion_point(field_release:fwd.ForwardRsp.message)
  
  return message_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void ForwardRsp::set_allocated_message(::std::string* message) {
  if (message != NULL) {
    
  } else {
    
  }
  message_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), message);
  // @@protoc_insertion_point(field_set_allocated:fwd.ForwardRsp.message)
}

// bytes response_frame = 3;
inline void ForwardRsp::clear_response_frame() {
  response_frame_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& ForwardRsp::response_frame() const {
  // @@protoc_insertion_point(field_get:fwd.ForwardRsp.response_frame)
  return response_frame_.GetNoArena();
}
inline void ForwardRsp::set_response_frame(const ::std::string& value) {
  
  response_frame_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:fwd.ForwardRsp.response_frame)
}
#if LANG_CXX11
inline void ForwardRsp::set_response_frame(::std::string&& value) {
  
  response_frame_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:fwd.ForwardRsp.response_frame)
}
#endif
inline void ForwardRsp::set_response_frame(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  response_frame_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:fwd.ForwardRsp.response_frame)
}
inline void ForwardRsp::set_response_frame(const void* value, size_t size) {
  
  response_frame_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:fwd.ForwardRsp.response_frame)
}
inline ::std::string* ForwardRsp::mutable_response_frame() {
  
  // @@protoc_insertion_point(field_mutable:fwd.ForwardRsp.response_frame)
  return response_frame_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* ForwardRsp::release_response_frame() {
  // @@protoc_insertion_point(field_release:fwd.ForwardRsp.response_frame)
  
  return response_frame_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void ForwardRsp::set_allocated_response_frame(::std::string* response_frame) {
  if (response_frame != NULL) {
    
  } else {
    
  }
  response_frame_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), response_frame);
  // @@protoc_insertion_point(field_set_allocated:fwd.ForwardRsp.response_frame)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace fwd

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_forward_2eproto__INCLUDED
