// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: gateway_push.proto

#ifndef PROTOBUF_gateway_5fpush_2eproto__INCLUDED
#define PROTOBUF_gateway_5fpush_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3005000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/service.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace protobuf_gateway_5fpush_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[3];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
void InitDefaultsPushMessageImpl();
void InitDefaultsPushMessage();
void InitDefaultsPushBatchRequestImpl();
void InitDefaultsPushBatchRequest();
void InitDefaultsPushBatchResponseImpl();
void InitDefaultsPushBatchResponse();
inline void InitDefaults() {
  InitDefaultsPushMessage();
  InitDefaultsPushBatchRequest();
  InitDefaultsPushBatchResponse();
}
}  // namespace protobuf_gateway_5fpush_2eproto
namespace gwpush {
class PushBatchRequest;
class PushBatchRequestDefaultTypeInternal;
extern PushBatchRequestDefaultTypeInternal _PushBatchRequest_default_instance_;
class PushBatchResponse;
class PushBatchResponseDefaultTypeInternal;
extern PushBatchResponseDefaultTypeInternal _PushBatchResponse_default_instance_;
class PushMessage;
class PushMessageDefaultTypeInternal;
extern PushMessageDefaultTypeInternal _PushMessage_default_instance_;
}  // namespace gwpush
namespace gwpush {

// ===================================================================

class PushMessage : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:gwpush.PushMessage) */ {
 public:
  PushMessage();
  virtual ~PushMessage();

  PushMessage(const PushMessage& from);

  inline PushMessage& operator=(const PushMessage& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  PushMessage(PushMessage&& from) noexcept
    : PushMessage() {
    *this = ::std::move(from);
  }

  inline PushMessage& operator=(PushMessage&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const PushMessage& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const PushMessage* internal_default_instance() {
    return reinterpret_cast<const PushMessage*>(
               &_PushMessage_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    0;

  void Swap(PushMessage* other);
  friend void swap(PushMessage& a, PushMessage& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline PushMessage* New() const PROTOBUF_FINAL { return New(NULL); }

  PushMessage* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const PushMessage& from);
  void MergeFrom(const PushMessage& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(PushMessage* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // string session_id = 2;
  void clear_session_id();
  static const int kSessionIdFieldNumber = 2;
  const ::std::string& session_id() const;
  void set_session_id(const ::std::string& value);
  #if LANG_CXX11
  void set_session_id(::std::string&& value);
  #endif
  void set_session_id(const char* value);
  void set_session_id(const char* value, size_t size);
  ::std::string* mutable_session_id();
  ::std::string* release_session_id();
  void set_allocated_session_id(::std::string* session_id);

  // string message_type = 4;
  void clear_message_type();
  static const int kMessageTypeFieldNumber = 4;
  const ::std::string& message_type() const;
  void set_message_type(const ::std::string& value);
  #if LANG_CXX11
  void set_message_type(::std::string&& value);
  #endif
  void set_message_type(const char* value);
  void set_message_type(const char* value, size_t size);
  ::std::string* mutable_message_type();
  ::std::string* release_message_type();
  void set_allocated_message_type(::std::string* message_type);

  // bytes payload = 5;
  void clear_payload();
  static const int kPayloadFieldNumber = 5;
  const ::std::string& payload() const;
  void set_payload(const ::std::string& value);
  #if LANG_CXX11
  void set_payload(::std::string&& value);
  #endif
  void set_payload(const char* value);
  void set_payload(const void* value, size_t size);
  ::std::string* mutable_payload();
  ::std::string* release_payload();
  void set_allocated_payload(::std::string* payload);

  // uint64 player_id = 1;
  void clear_player_id();
  static const int kPlayerIdFieldNumber = 1;
  ::google::protobuf::uint64 player_id() const;
  void set_player_id(::google::protobuf::uint64 value);

  // uint64 server_seq = 3;
  void clear_server_seq();
  static const int kServerSeqFieldNumber = 3;
  ::google::protobuf::uint64 server_seq() const;
  void set_server_seq(::google::protobuf::uint64 value);

  // bool reliable = 6;
  void clear_reliable();
  static const int kReliableFieldNumber = 6;
  bool reliable() const;
  void set_reliable(bool value);

  // bool coalescable = 7;
  void clear_coalescable();
  static const int kCoalescableFieldNumber = 7;
  bool coalescable() const;
  void set_coalescable(bool value);

  // @@protoc_insertion_point(class_scope:gwpush.PushMessage)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr session_id_;
  ::google::protobuf::internal::ArenaStringPtr message_type_;
  ::google::protobuf::internal::ArenaStringPtr payload_;
  ::google::protobuf::uint64 player_id_;
  ::google::protobuf::uint64 server_seq_;
  bool reliable_;
  bool coalescable_;
  mutable int _cached_size_;
  friend struct ::protobuf_gateway_5fpush_2eproto::TableStruct;
  friend void ::protobuf_gateway_5fpush_2eproto::InitDefaultsPushMessageImpl();
};
// -------------------------------------------------------------------

class PushBatchRequest : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:gwpush.PushBatchRequest) */ {
 public:
  PushBatchRequest();
  virtual ~PushBatchRequest();

  PushBatchRequest(const PushBatchRequest& from);

  inline PushBatchRequest& operator=(const PushBatchRequest& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  PushBatchRequest(PushBatchRequest&& from) noexcept
    : PushBatchRequest() {
    *this = ::std::move(from);
  }

  inline PushBatchRequest& operator=(PushBatchRequest&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const PushBatchRequest& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const PushBatchRequest* internal_default_instance() {
    return reinterpret_cast<const PushBatchRequest*>(
               &_PushBatchRequest_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    1;

  void Swap(PushBatchRequest* other);
  friend void swap(PushBatchRequest& a, PushBatchRequest& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline PushBatchRequest* New() const PROTOBUF_FINAL { return New(NULL); }

  PushBatchRequest* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const PushBatchRequest& from);
  void MergeFrom(const PushBatchRequest& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(PushBatchRequest* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .gwpush.PushMessage messages = 2;
  int messages_size() const;
  void clear_messages();
  static const int kMessagesFieldNumber = 2;
  const ::gwpush::PushMessage& messages(int index) const;
  ::gwpush::PushMessage* mutable_messages(int index);
  ::gwpush::PushMessage* add_messages();
  ::google::protobuf::RepeatedPtrField< ::gwpush::PushMessage >*
      mutable_messages();
  const ::google::protobuf::RepeatedPtrField< ::gwpush::PushMessage >&
      messages() const;

  // string gateway_instance_id = 1;
  void clear_gateway_instance_id();
  static const int kGatewayInstanceIdFieldNumber = 1;
  const ::std::string& gateway_instance_id() const;
  void set_gateway_instance_id(const ::std::string& value);
  #if LANG_CXX11
  void set_gateway_instance_id(::std::string&& value);
  #endif
  void set_gateway_instance_id(const char* value);
  void set_gateway_instance_id(const char* value, size_t size);
  ::std::string* mutable_gateway_instance_id();
  ::std::string* release_gateway_instance_id();
  void set_allocated_gateway_instance_id(::std::string* gateway_instance_id);

  // @@protoc_insertion_point(class_scope:gwpush.PushBatchRequest)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedPtrField< ::gwpush::PushMessage > messages_;
  ::google::protobuf::internal::ArenaStringPtr gateway_instance_id_;
  mutable int _cached_size_;
  friend struct ::protobuf_gateway_5fpush_2eproto::TableStruct;
  friend void ::protobuf_gateway_5fpush_2eproto::InitDefaultsPushBatchRequestImpl();
};
// -------------------------------------------------------------------

class PushBatchResponse : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:gwpush.PushBatchResponse) */ {
 public:
  PushBatchResponse();
  virtual ~PushBatchResponse();

  PushBatchResponse(const PushBatchResponse& from);

  inline PushBatchResponse& operator=(const PushBatchResponse& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  PushBatchResponse(PushBatchResponse&& from) noexcept
    : PushBatchResponse() {
    *this = ::std::move(from);
  }

  inline PushBatchResponse& operator=(PushBatchResponse&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const PushBatchResponse& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const PushBatchResponse* internal_default_instance() {
    return reinterpret_cast<const PushBatchResponse*>(
               &_PushBatchResponse_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    2;

  void Swap(PushBatchResponse* other);
  friend void swap(PushBatchResponse& a, PushBatchResponse& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline PushBatchResponse* New() const PROTOBUF_FINAL { return New(NULL); }

  PushBatchResponse* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const PushBatchResponse& from);
  void MergeFrom(const PushBatchResponse& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(PushBatchResponse* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // string message = 2;
  void clear_message();
  static const int kMessageFieldNumber = 2;
  const ::std::string& message() const;
  void set_message(const ::std::string& value);
  #if LANG_CXX11
  void set_message(::std::string&& value);
  #endif
  void set_message(const char* value);
  void set_message(const char* value, size_t size);
  ::std::string* mutable_message();
  ::std::string* release_message();
  void set_allocated_message(::std::string* message);

  // bool ok = 1;
  void clear_ok();
  static const int kOkFieldNumber = 1;
  bool ok() const;
  void set_ok(bool value);

  // uint32 accepted = 3;
  void clear_accepted();
  static const int kAcceptedFieldNumber = 3;
  ::google::protobuf::uint32 accepted() const;
  void set_accepted(::google::protobuf::uint32 value);

  // uint32 rejected = 4;
  void clear_rejected();
  static const int kRejectedFieldNumber = 4;
  ::google::protobuf::uint32 rejected() const;
  void set_rejected(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:gwpush.PushBatchResponse)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr message_;
  bool ok_;
  ::google::protobuf::uint32 accepted_;
  ::google::protobuf::uint32 rejected_;
  mutable int _cached_size_;
  friend struct ::protobuf_gateway_5fpush_2eproto::TableStruct;
  friend void ::protobuf_gateway_5fpush_2eproto::InitDefaultsPushBatchResponseImpl();
};
// ===================================================================

class GatewayPushService_Stub;

class GatewayPushService : public ::google::protobuf::Service {
 protected:
  // This class should be treated as an abstract interface.
  inline GatewayPushService() {};
 public:
  virtual ~GatewayPushService();

  typedef GatewayPushService_Stub Stub;

  static const ::google::protobuf::ServiceDescriptor* descriptor();

  virtual void PushBatch(::google::protobuf::RpcController* controller,
                       const ::gwpush::PushBatchRequest* request,
                       ::gwpush::PushBatchResponse* response,
                       ::google::protobuf::Closure* done);

  // implements Service ----------------------------------------------

  const ::google::protobuf::ServiceDescriptor* GetDescriptor();
  void CallMethod(const ::google::protobuf::MethodDescriptor* method,
                  ::google::protobuf::RpcController* controller,
                  const ::google::protobuf::Message* request,
                  ::google::protobuf::Message* response,
                  ::google::protobuf::Closure* done);
  const ::google::protobuf::Message& GetRequestPrototype(
    const ::google::protobuf::MethodDescriptor* method) const;
  const ::google::protobuf::Message& GetResponsePrototype(
    const ::google::protobuf::MethodDescriptor* method) const;

 private:
  GOOGLE_DISALLOW_EVIL_CONSTRUCTORS(GatewayPushService);
};

class GatewayPushService_Stub : public GatewayPushService {
 public:
  GatewayPushService_Stub(::google::protobuf::RpcChannel* channel);
  GatewayPushService_Stub(::google::protobuf::RpcChannel* channel,
                   ::google::protobuf::Service::ChannelOwnership ownership);
  ~GatewayPushService_Stub();

  inline ::google::protobuf::RpcChannel* channel() { return channel_; }

  // implements GatewayPushService ------------------------------------------

  void PushBatch(::google::protobuf::RpcController* controller,
                       const ::gwpush::PushBatchRequest* request,
                       ::gwpush::PushBatchResponse* response,
                       ::google::protobuf::Closure* done);
 private:
  ::google::protobuf::RpcChannel* channel_;
  bool owns_channel_;
  GOOGLE_DISALLOW_EVIL_CONSTRUCTORS(GatewayPushService_Stub);
};


// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// PushMessage

// uint64 player_id = 1;
inline void PushMessage::clear_player_id() {
  player_id_ = GOOGLE_ULONGLONG(0);
}
inline ::google::protobuf::uint64 PushMessage::player_id() const {
  // @@protoc_insertion_point(field_get:gwpush.PushMessage.player_id)
  return player_id_;
}
inline void PushMessage::set_player_id(::google::protobuf::uint64 value) {
  
  player_id_ = value;
  // @@protoc_insertion_point(field_set:gwpush.PushMessage.player_id)
}

// string session_id = 2;
inline void PushMessage::clear_session_id() {
  session_id_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& PushMessage::session_id() const {
  // @@protoc_insertion_point(field_get:gwpush.PushMessage.session_id)
  return session_id_.GetNoArena();
}
inline void PushMessage::set_session_id(const ::std::string& value) {
  
  session_id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:gwpush.PushMessage.session_id)
}
#if LANG_CXX11
inline void PushMessage::set_session_id(::std::string&& value) {
  
  session_id_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:gwpush.PushMessage.session_id)
}
#endif
inline void PushMessage::set_session_id(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  session_id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:gwpush.PushMessage.session_id)
}
inline void PushMessage::set_session_id(const char* value, size_t size) {
  
  session_id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:gwpush.PushMessage.session_id)
}
inline ::std::string* PushMessage::mutable_session_id() {
  
  // @@protoc_insertion_point(field_mutable:gwpush.PushMessage.session_id)
  return session_id_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* PushMessage::release_session_id() {
  // @@protoc_insertion_point(field_release:gwpush.PushMessage.session_id)
  
  return session_id_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void PushMessage::set_allocated_session_id(::std::string* session_id) {
  if (session_id != NULL) {
    
  } else {
    
  }
  session_id_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), session_id);
  // @@protoc_insertion_point(field_set_allocated:gwpush.PushMessage.session_id)
}

// uint64 server_seq = 3;
inline void PushMessage::clear_server_seq() {
  server_seq_ = GOOGLE_ULONGLONG(0);
}
inline ::google::protobuf::uint64 PushMessage::server_seq() const {
  // @@protoc_insertion_point(field_get:gwpush.PushMessage.server_seq)
  return server_seq_;
}
inline void PushMessage::set_server_seq(::google::protobuf::uint64 value) {
  
  server_seq_ = value;
  // @@protoc_insertion_point(field_set:gwpush.PushMessage.server_seq)
}

// string message_type = 4;
inline void PushMessage::clear_message_type() {
  message_type_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& PushMessage::message_type() const {
  // @@protoc_insertion_point(field_get:gwpush.PushMessage.message_type)
  return message_type_.GetNoArena();
}
inline void PushMessage::set_message_type(const ::std::string& value) {
  
  message_type_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:gwpush.PushMessage.message_type)
}
#if LANG_CXX11
inline void PushMessage::set_message_type(::std::string&& value) {
  
  message_type_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:gwpush.PushMessage.message_type)
}
#endif
inline void PushMessage::set_message_type(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  message_type_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:gwpush.PushMessage.message_type)
}
inline void PushMessage::set_message_type(const char* value, size_t size) {
  
  message_type_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:gwpush.PushMessage.message_type)
}
inline ::std::string* PushMessage::mutable_message_type() {
  
  // @@protoc_insertion_point(field_mutable:gwpush.PushMessage.message_type)
  return message_type_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* PushMessage::release_message_type() {
  // @@protoc_insertion_point(field_release:gwpush.PushMessage.message_type)
  
  return message_type_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void PushMessage::set_allocated_message_type(::std::string* message_type) {
  if (message_type != NULL) {
    
  } else {
    
  }
  message_type_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), message_type);
  // @@protoc_insertion_point(field_set_allocated:gwpush.PushMessage.message_type)
}

// bytes payload = 5;
inline void PushMessage::clear_payload() {
  payload_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& PushMessage::payload() const {
  // @@protoc_insertion_point(field_get:gwpush.PushMessage.payload)
  return payload_.GetNoArena();
}
inline void PushMessage::set_payload(const ::std::string& value) {
  
  payload_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:gwpush.PushMessage.payload)
}
#if LANG_CXX11
inline void PushMessage::set_payload(::std::string&& value) {
  
  payload_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:gwpush.PushMessage.payload)
}
#endif
inline void PushMessage::set_payload(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  payload_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:gwpush.PushMessage.payload)
}
inline void PushMessage::set_payload(const void* value, size_t size) {
  
  payload_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:gwpush.PushMessage.payload)
}
inline ::std::string* PushMessage::mutable_payload() {
  
  // @@protoc_insertion_point(field_mutable:gwpush.PushMessage.payload)
  return payload_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* PushMessage::release_payload() {
  // @@protoc_insertion_point(field_release:gwpush.PushMessage.payload)
  
  return payload_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void PushMessage::set_allocated_payload(::std::string* payload) {
  if (payload != NULL) {
    
  } else {
    
  }
  payload_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), payload);
  // @@protoc_insertion_point(field_set_allocated:gwpush.PushMessage.payload)
}

// bool reliable = 6;
inline void PushMessage::clear_reliable() {
  reliable_ = false;
}
inline bool PushMessage::reliable() const {
  // @@protoc_insertion_point(field_get:gwpush.PushMessage.reliable)
  return reliable_;
}
inline void PushMessage::set_reliable(bool value) {
  
  reliable_ = value;
  // @@protoc_insertion_point(field_set:gwpush.PushMessage.reliable)
}

// bool coalescable = 7;
inline void PushMessage::clear_coalescable() {
  coalescable_ = false;
}
inline bool PushMessage::coalescable() const {
  // @@protoc_insertion_point(field_get:gwpush.PushMessage.coalescable)
  return coalescable_;
}
inline void PushMessage::set_coalescable(bool value) {
  
  coalescable_ = value;
  // @@protoc_insertion_point(field_set:gwpush.PushMessage.coalescable)
}

// -------------------------------------------------------------------

// PushBatchRequest

// string gateway_instance_id = 1;
inline void PushBatchRequest::clear_gateway_instance_id() {
  gateway_instance_id_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& PushBatchRequest::gateway_instance_id() const {
  // @@protoc_insertion_point(field_get:gwpush.PushBatchRequest.gateway_instance_id)
  return gateway_instance_id_.GetNoArena();
}
inline void PushBatchRequest::set_gateway_instance_id(const ::std::string& value) {
  
  gateway_instance_id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:gwpush.PushBatchRequest.gateway_instance_id)
}
#if LANG_CXX11
inline void PushBatchRequest::set_gateway_instance_id(::std::string&& value) {
  
  gateway_instance_id_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:gwpush.PushBatchRequest.gateway_instance_id)
}
#endif
inline void PushBatchRequest::set_gateway_instance_id(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  gateway_instance_id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:gwpush.PushBatchRequest.gateway_instance_id)
}
inline void PushBatchRequest::set_gateway_instance_id(const char* value, size_t size) {
  
  gateway_instance_id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:gwpush.PushBatchRequest.gateway_instance_id)
}
inline ::std::string* PushBatchRequest::mutable_gateway_instance_id() {
  
  // @@protoc_insertion_point(field_mutable:gwpush.PushBatchRequest.gateway_instance_id)
  return gateway_instance_id_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* PushBatchRequest::release_gateway_instance_id() {
  // @@protoc_insertion_point(field_release:gwpush.PushBatchRequest.gateway_instance_id)
  
  return gateway_instance_id_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void PushBatchRequest::set_allocated_gateway_instance_id(::std::string* gateway_instance_id) {
  if (gateway_instance_id != NULL) {
    
  } else {
    
  }
  gateway_instance_id_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), gateway_instance_id);
  // @@protoc_insertion_point(field_set_allocated:gwpush.PushBatchRequest.gateway_instance_id)
}

// repeated .gwpush.PushMessage messages = 2;
inline int PushBatchRequest::messages_size() const {
  return messages_.size();
}
inline void PushBatchRequest::clear_messages() {
  messages_.Clear();
}
inline const ::gwpush::PushMessage& PushBatchRequest::messages(int index) const {
  // @@protoc_insertion_point(field_get:gwpush.PushBatchRequest.messages)
  return messages_.Get(index);
}
inline ::gwpush::PushMessage* PushBatchRequest::mutable_messages(int index) {
  // @@protoc_insertion_point(field_mutable:gwpush.PushBatchRequest.messages)
  return messages_.Mutable(index);
}
inline ::gwpush::PushMessage* PushBatchRequest::add_messages() {
  // @@protoc_insertion_point(field_add:gwpush.PushBatchRequest.messages)
  return messages_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::gwpush::PushMessage >*
PushBatchRequest::mutable_messages() {
  // @@protoc_insertion_point(field_mutable_list:gwpush.PushBatchRequest.messages)
  return &messages_;
}
inline const ::google::protobuf::RepeatedPtrField< ::gwpush::PushMessage >&
PushBatchRequest::messages() const {
  // @@protoc_insertion_point(field_list:gwpush.PushBatchRequest.messages)
  return messages_;
}

// -------------------------------------------------------------------

// PushBatchResponse

// bool ok = 1;
inline void PushBatchResponse::clear_ok() {
  ok_ = false;
}
inline bool PushBatchResponse::ok() const {
  // @@protoc_insertion_point(field_get:gwpush.PushBatchResponse.ok)
  return ok_;
}
inline void PushBatchResponse::set_ok(bool value) {
  
  ok_ = value;
  // @@protoc_insertion_point(field_set:gwpush.PushBatchResponse.ok)
}

// string message = 2;
inline void PushBatchResponse::clear_message() {
  message_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& PushBatchResponse::message() const {
  // @@protoc_insertion_point(field_get:gwpush.PushBatchResponse.message)
  return message_.GetNoArena();
}
inline void PushBatchResponse::set_message(const ::std::string& value) {
  
  message_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:gwpush.PushBatchResponse.message)
}
#if LANG_CXX11
inline void PushBatchResponse::set_message(::std::string&& value) {
  
  message_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:gwpush.PushBatchResponse.message)
}
#endif
inline void PushBatchResponse::set_message(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  message_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:gwpush.PushBatchResponse.message)
}
inline void PushBatchResponse::set_message(const char* value, size_t size) {
  
  message_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:gwpush.PushBatchResponse.message)
}
inline ::std::string* PushBatchResponse::mutable_message() {
  
  // @@protoc_insertion_point(field_mutable:gwpush.PushBatchResponse.message)
  return message_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* PushBatchResponse::release_message() {
  // @@protoc_insertion_point(field_release:gwpush.PushBatchResponse.message)
  
  return message_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void PushBatchResponse::set_allocated_message(::std::string* message) {
  if (message != NULL) {
    
  } else {
    
  }
  message_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), message);
  // @@protoc_insertion_point(field_set_allocated:gwpush.PushBatchResponse.message)
}

// uint32 accepted = 3;
inline void PushBatchResponse::clear_accepted() {
  accepted_ = 0u;
}
inline ::google::protobuf::uint32 PushBatchResponse::accepted() const {
  // @@protoc_insertion_point(field_get:gwpush.PushBatchResponse.accepted)
  return accepted_;
}
inline void PushBatchResponse::set_accepted(::google::protobuf::uint32 value) {
  
  accepted_ = value;
  // @@protoc_insertion_point(field_set:gwpush.PushBatchResponse.accepted)
}

// uint32 rejected = 4;
inline void PushBatchResponse::clear_rejected() {
  rejected_ = 0u;
}
inline ::google::protobuf::uint32 PushBatchResponse::rejected() const {
  // @@protoc_insertion_point(field_get:gwpush.PushBatchResponse.rejected)
  return rejected_;
}
inline void PushBatchResponse::set_rejected(::google::protobuf::uint32 value) {
  
  rejected_ = value;
  // @@protoc_insertion_point(field_set:gwpush.PushBatchResponse.rejected)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace gwpush

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_gateway_5fpush_2eproto__INCLUDED
