// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: gateway_push.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_gateway_5fpush_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_gateway_5fpush_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3012000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3012004 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/service.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_gateway_5fpush_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_gateway_5fpush_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxillaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[5]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_gateway_5fpush_2eproto;
namespace gwpush {
class KickConnectionRequest;
class KickConnectionRequestDefaultTypeInternal;
extern KickConnectionRequestDefaultTypeInternal _KickConnectionRequest_default_instance_;
class KickConnectionResponse;
class KickConnectionResponseDefaultTypeInternal;
extern KickConnectionResponseDefaultTypeInternal _KickConnectionResponse_default_instance_;
class PushBatchRequest;
class PushBatchRequestDefaultTypeInternal;
extern PushBatchRequestDefaultTypeInternal _PushBatchRequest_default_instance_;
class PushBatchResponse;
class PushBatchResponseDefaultTypeInternal;
extern PushBatchResponseDefaultTypeInternal _PushBatchResponse_default_instance_;
class PushMessage;
class PushMessageDefaultTypeInternal;
extern PushMessageDefaultTypeInternal _PushMessage_default_instance_;
}  // namespace gwpush
PROTOBUF_NAMESPACE_OPEN
template<> ::gwpush::KickConnectionRequest* Arena::CreateMaybeMessage<::gwpush::KickConnectionRequest>(Arena*);
template<> ::gwpush::KickConnectionResponse* Arena::CreateMaybeMessage<::gwpush::KickConnectionResponse>(Arena*);
template<> ::gwpush::PushBatchRequest* Arena::CreateMaybeMessage<::gwpush::PushBatchRequest>(Arena*);
template<> ::gwpush::PushBatchResponse* Arena::CreateMaybeMessage<::gwpush::PushBatchResponse>(Arena*);
template<> ::gwpush::PushMessage* Arena::CreateMaybeMessage<::gwpush::PushMessage>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace gwpush {

// ===================================================================

class PushMessage PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:gwpush.PushMessage) */ {
 public:
  inline PushMessage() : PushMessage(nullptr) {};
  virtual ~PushMessage();

  PushMessage(const PushMessage& from);
  PushMessage(PushMessage&& from) noexcept
    : PushMessage() {
    *this = ::std::move(from);
  }

  inline PushMessage& operator=(const PushMessage& from) {
    CopyFrom(from);
    return *this;
  }
  inline PushMessage& operator=(PushMessage&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const PushMessage& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const PushMessage* internal_default_instance() {
    return reinterpret_cast<const PushMessage*>(
               &_PushMessage_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(PushMessage& a, PushMessage& b) {
    a.Swap(&b);
  }
  inline void Swap(PushMessage* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(PushMessage* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline PushMessage* New() const final {
    return CreateMaybeMessage<PushMessage>(nullptr);
  }

  PushMessage* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<PushMessage>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const PushMessage& from);
  void MergeFrom(const PushMessage& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(PushMessage* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "gwpush.PushMessage";
  }
  protected:
  explicit PushMessage(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_gateway_5fpush_2eproto);
    return ::descriptor_table_gateway_5fpush_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kSessionIdFieldNumber = 2,
    kMessageTypeFieldNumber = 4,
    kPayloadFieldNumber = 5,
    kFenceTokenFieldNumber = 8,
    kPlayerIdFieldNumber = 1,
    kServerSeqFieldNumber = 3,
    kGenerationFieldNumber = 9,
    kReliableFieldNumber = 6,
    kCoalescableFieldNumber = 7,
  };
  // string session_id = 2;
  void clear_session_id();
  const std::string& session_id() const;
  void set_session_id(const std::string& value);
  void set_session_id(std::string&& value);
  void set_session_id(const char* value);
  void set_session_id(const char* value, size_t size);
  std::string* mutable_session_id();
  std::string* release_session_id();
  void set_allocated_session_id(std::string* session_id);
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  std::string* unsafe_arena_release_session_id();
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  void unsafe_arena_set_allocated_session_id(
      std::string* session_id);
  private:
  const std::string& _internal_session_id() const;
  void _internal_set_session_id(const std::string& value);
  std::string* _internal_mutable_session_id();
  public:

  // string message_type = 4;
  void clear_message_type();
  const std::string& message_type() const;
  void set_message_type(const std::string& value);
  void set_message_type(std::string&& value);
  void set_message_type(const char* value);
  void set_message_type(const char* value, size_t size);
  std::string* mutable_message_type();
  std::string* release_message_type();
  void set_allocated_message_type(std::string* message_type);
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  std::string* unsafe_arena_release_message_type();
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  void unsafe_arena_set_allocated_message_type(
      std::string* message_type);
  private:
  const std::string& _internal_message_type() const;
  void _internal_set_message_type(const std::string& value);
  std::string* _internal_mutable_message_type();
  public:

  // bytes payload = 5;
  void clear_payload();
  const std::string& payload() const;
  void set_payload(const std::string& value);
  void set_payload(std::string&& value);
  void set_payload(const char* value);
  void set_payload(const void* value, size_t size);
  std::string* mutable_payload();
  std::string* release_payload();
  void set_allocated_payload(std::string* payload);
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  std::string* unsafe_arena_release_payload();
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  void unsafe_arena_set_allocated_payload(
      std::string* payload);
  private:
  const std::string& _internal_payload() const;
  void _internal_set_payload(const std::string& value);
  std::string* _internal_mutable_payload();
  public:

  // string fence_token = 8;
  void clear_fence_token();
  const std::string& fence_token() const;
  void set_fence_token(const std::string& value);
  void set_fence_token(std::string&& value);
  void set_fence_token(const char* value);
  void set_fence_token(const char* value, size_t size);
  std::string* mutable_fence_token();
  std::string* release_fence_token();
  void set_allocated_fence_token(std::string* fence_token);
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  std::string* unsafe_arena_release_fence_token();
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  void unsafe_arena_set_allocated_fence_token(
      std::string* fence_token);
  private:
  const std::string& _internal_fence_token() const;
  void _internal_set_fence_token(const std::string& value);
  std::string* _internal_mutable_fence_token();
  public:

  // uint64 player_id = 1;
  void clear_player_id();
  ::PROTOBUF_NAMESPACE_ID::uint64 player_id() const;
  void set_player_id(::PROTOBUF_NAMESPACE_ID::uint64 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint64 _internal_player_id() const;
  void _internal_set_player_id(::PROTOBUF_NAMESPACE_ID::uint64 value);
  public:

  // uint64 server_seq = 3;
  void clear_server_seq();
  ::PROTOBUF_NAMESPACE_ID::uint64 server_seq() const;
  void set_server_seq(::PROTOBUF_NAMESPACE_ID::uint64 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint64 _internal_server_seq() const;
  void _internal_set_server_seq(::PROTOBUF_NAMESPACE_ID::uint64 value);
  public:

  // uint64 generation = 9;
  void clear_generation();
  ::PROTOBUF_NAMESPACE_ID::uint64 generation() const;
  void set_generation(::PROTOBUF_NAMESPACE_ID::uint64 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint64 _internal_generation() const;
  void _internal_set_generation(::PROTOBUF_NAMESPACE_ID::uint64 value);
  public:

  // bool reliable = 6;
  void clear_reliable();
  bool reliable() const;
  void set_reliable(bool value);
  private:
  bool _internal_reliable() const;
  void _internal_set_reliable(bool value);
  public:

  // bool coalescable = 7;
  void clear_coalescable();
  bool coalescable() const;
  void set_coalescable(bool value);
  private:
  bool _internal_coalescable() const;
  void _internal_set_coalescable(bool value);
  public:

  // @@protoc_insertion_point(class_scope:gwpush.PushMessage)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr session_id_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr message_type_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr payload_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr fence_token_;
  ::PROTOBUF_NAMESPACE_ID::uint64 player_id_;
  ::PROTOBUF_NAMESPACE_ID::uint64 server_seq_;
  ::PROTOBUF_NAMESPACE_ID::uint64 generation_;
  bool reliable_;
  bool coalescable_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_gateway_5fpush_2eproto;
};
// -------------------------------------------------------------------

class PushBatchRequest PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:gwpush.PushBatchRequest) */ {
 public:
  inline PushBatchRequest() : PushBatchRequest(nullptr) {};
  virtual ~PushBatchRequest();

  PushBatchRequest(const PushBatchRequest& from);
  PushBatchRequest(PushBatchRequest&& from) noexcept
    : PushBatchRequest() {
    *this = ::std::move(from);
  }

  inline PushBatchRequest& operator=(const PushBatchRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline PushBatchRequest& operator=(PushBatchRequest&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const PushBatchRequest& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const PushBatchRequest* internal_default_instance() {
    return reinterpret_cast<const PushBatchRequest*>(
               &_PushBatchRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(PushBatchRequest& a, PushBatchRequest& b) {
    a.Swap(&b);
  }
  inline void Swap(PushBatchRequest* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(PushBatchRequest* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline PushBatchRequest* New() const final {
    return CreateMaybeMessage<PushBatchRequest>(nullptr);
  }

  PushBatchRequest* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<PushBatchRequest>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const PushBatchRequest& from);
  void MergeFrom(const PushBatchRequest& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(PushBatchRequest* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "gwpush.PushBatchRequest";
  }
  protected:
  explicit PushBatchRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_gateway_5fpush_2eproto);
    return ::descriptor_table_gateway_5fpush_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kMessagesFieldNumber = 2,
    kGatewayInstanceIdFieldNumber = 1,
  };
  // repeated .gwpush.PushMessage messages = 2;
  int messages_size() const;
  private:
  int _internal_messages_size() const;
  public:
  void clear_messages();
  ::gwpush::PushMessage* mutable_messages(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::gwpush::PushMessage >*
      mutable_messages();
  private:
  const ::gwpush::PushMessage& _internal_messages(int index) const;
  ::gwpush::PushMessage* _internal_add_messages();
  public:
  const ::gwpush::PushMessage& messages(int index) const;
  ::gwpush::PushMessage* add_messages();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::gwpush::PushMessage >&
      messages() const;

  // string gateway_instance_id = 1;
  void clear_gateway_instance_id();
  const std::string& gateway_instance_id() const;
  void set_gateway_instance_id(const std::string& value);
  void set_gateway_instance_id(std::string&& value);
  void set_gateway_instance_id(const char* value);
  void set_gateway_instance_id(const char* value, size_t size);
  std::string* mutable_gateway_instance_id();
  std::string* release_gateway_instance_id();
  void set_allocated_gateway_instance_id(std::string* gateway_instance_id);
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  std::string* unsafe_arena_release_gateway_instance_id();
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  void unsafe_arena_set_allocated_gateway_instance_id(
      std::string* gateway_instance_id);
  private:
  const std::string& _internal_gateway_instance_id() const;
  void _internal_set_gateway_instance_id(const std::string& value);
  std::string* _internal_mutable_gateway_instance_id();
  public:

  // @@protoc_insertion_point(class_scope:gwpush.PushBatchRequest)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::gwpush::PushMessage > messages_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr gateway_instance_id_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_gateway_5fpush_2eproto;
};
// -------------------------------------------------------------------

class PushBatchResponse PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:gwpush.PushBatchResponse) */ {
 public:
  inline PushBatchResponse() : PushBatchResponse(nullptr) {};
  virtual ~PushBatchResponse();

  PushBatchResponse(const PushBatchResponse& from);
  PushBatchResponse(PushBatchResponse&& from) noexcept
    : PushBatchResponse() {
    *this = ::std::move(from);
  }

  inline PushBatchResponse& operator=(const PushBatchResponse& from) {
    CopyFrom(from);
    return *this;
  }
  inline PushBatchResponse& operator=(PushBatchResponse&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const PushBatchResponse& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const PushBatchResponse* internal_default_instance() {
    return reinterpret_cast<const PushBatchResponse*>(
               &_PushBatchResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(PushBatchResponse& a, PushBatchResponse& b) {
    a.Swap(&b);
  }
  inline void Swap(PushBatchResponse* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(PushBatchResponse* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline PushBatchResponse* New() const final {
    return CreateMaybeMessage<PushBatchResponse>(nullptr);
  }

  PushBatchResponse* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<PushBatchResponse>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const PushBatchResponse& from);
  void MergeFrom(const PushBatchResponse& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(PushBatchResponse* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "gwpush.PushBatchResponse";
  }
  protected:
  explicit PushBatchResponse(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_gateway_5fpush_2eproto);
    return ::descriptor_table_gateway_5fpush_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kMessageFieldNumber = 2,
    kOkFieldNumber = 1,
    kAcceptedFieldNumber = 3,
    kRejectedFieldNumber = 4,
  };
  // string message = 2;
  void clear_message();
  const std::string& message() const;
  void set_message(const std::string& value);
  void set_message(std::string&& value);
  void set_message(const char* value);
  void set_message(const char* value, size_t size);
  std::string* mutable_message();
  std::string* release_message();
  void set_allocated_message(std::string* message);
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  std::string* unsafe_arena_release_message();
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  void unsafe_arena_set_allocated_message(
      std::string* message);
  private:
  const std::string& _internal_message() const;
  void _internal_set_message(const std::string& value);
  std::string* _internal_mutable_message();
  public:

  // bool ok = 1;
  void clear_ok();
  bool ok() const;
  void set_ok(bool value);
  private:
  bool _internal_ok() const;
  void _internal_set_ok(bool value);
  public:

  // uint32 accepted = 3;
  void clear_accepted();
  ::PROTOBUF_NAMESPACE_ID::uint32 accepted() const;
  void set_accepted(::PROTOBUF_NAMESPACE_ID::uint32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint32 _internal_accepted() const;
  void _internal_set_accepted(::PROTOBUF_NAMESPACE_ID::uint32 value);
  public:

  // uint32 rejected = 4;
  void clear_rejected();
  ::PROTOBUF_NAMESPACE_ID::uint32 rejected() const;
  void set_rejected(::PROTOBUF_NAMESPACE_ID::uint32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint32 _internal_rejected() const;
  void _internal_set_rejected(::PROTOBUF_NAMESPACE_ID::uint32 value);
  public:

  // @@protoc_insertion_point(class_scope:gwpush.PushBatchResponse)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr message_;
  bool ok_;
  ::PROTOBUF_NAMESPACE_ID::uint32 accepted_;
  ::PROTOBUF_NAMESPACE_ID::uint32 rejected_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_gateway_5fpush_2eproto;
};
// -------------------------------------------------------------------

class KickConnectionRequest PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:gwpush.KickConnectionRequest) */ {
 public:
  inline KickConnectionRequest() : KickConnectionRequest(nullptr) {};
  virtual ~KickConnectionRequest();

  KickConnectionRequest(const KickConnectionRequest& from);
  KickConnectionRequest(KickConnectionRequest&& from) noexcept
    : KickConnectionRequest() {
    *this = ::std::move(from);
  }

  inline KickConnectionRequest& operator=(const KickConnectionRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline KickConnectionRequest& operator=(KickConnectionRequest&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const KickConnectionRequest& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const KickConnectionRequest* internal_default_instance() {
    return reinterpret_cast<const KickConnectionRequest*>(
               &_KickConnectionRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  friend void swap(KickConnectionRequest& a, KickConnectionRequest& b) {
    a.Swap(&b);
  }
  inline void Swap(KickConnectionRequest* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(KickConnectionRequest* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline KickConnectionRequest* New() const final {
    return CreateMaybeMessage<KickConnectionRequest>(nullptr);
  }

  KickConnectionRequest* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<KickConnectionRequest>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const KickConnectionRequest& from);
  void MergeFrom(const KickConnectionRequest& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(KickConnectionRequest* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "gwpush.KickConnectionRequest";
  }
  protected:
  explicit KickConnectionRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_gateway_5fpush_2eproto);
    return ::descriptor_table_gateway_5fpush_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kSessionIdFieldNumber = 2,
    kReasonFieldNumber = 4,
    kPlayerIdFieldNumber = 1,
    kGenerationFieldNumber = 3,
  };
  // string session_id = 2;
  void clear_session_id();
  const std::string& session_id() const;
  void set_session_id(const std::string& value);
  void set_session_id(std::string&& value);
  void set_session_id(const char* value);
  void set_session_id(const char* value, size_t size);
  std::string* mutable_session_id();
  std::string* release_session_id();
  void set_allocated_session_id(std::string* session_id);
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  std::string* unsafe_arena_release_session_id();
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  void unsafe_arena_set_allocated_session_id(
      std::string* session_id);
  private:
  const std::string& _internal_session_id() const;
  void _internal_set_session_id(const std::string& value);
  std::string* _internal_mutable_session_id();
  public:

  // string reason = 4;
  void clear_reason();
  const std::string& reason() const;
  void set_reason(const std::string& value);
  void set_reason(std::string&& value);
  void set_reason(const char* value);
  void set_reason(const char* value, size_t size);
  std::string* mutable_reason();
  std::string* release_reason();
  void set_allocated_reason(std::string* reason);
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  std::string* unsafe_arena_release_reason();
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  void unsafe_arena_set_allocated_reason(
      std::string* reason);
  private:
  const std::string& _internal_reason() const;
  void _internal_set_reason(const std::string& value);
  std::string* _internal_mutable_reason();
  public:

  // uint64 player_id = 1;
  void clear_player_id();
  ::PROTOBUF_NAMESPACE_ID::uint64 player_id() const;
  void set_player_id(::PROTOBUF_NAMESPACE_ID::uint64 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint64 _internal_player_id() const;
  void _internal_set_player_id(::PROTOBUF_NAMESPACE_ID::uint64 value);
  public:

  // uint64 generation = 3;
  void clear_generation();
  ::PROTOBUF_NAMESPACE_ID::uint64 generation() const;
  void set_generation(::PROTOBUF_NAMESPACE_ID::uint64 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint64 _internal_generation() const;
  void _internal_set_generation(::PROTOBUF_NAMESPACE_ID::uint64 value);
  public:

  // @@protoc_insertion_point(class_scope:gwpush.KickConnectionRequest)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr session_id_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr reason_;
  ::PROTOBUF_NAMESPACE_ID::uint64 player_id_;
  ::PROTOBUF_NAMESPACE_ID::uint64 generation_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_gateway_5fpush_2eproto;
};
// -------------------------------------------------------------------

class KickConnectionResponse PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:gwpush.KickConnectionResponse) */ {
 public:
  inline KickConnectionResponse() : KickConnectionResponse(nullptr) {};
  virtual ~KickConnectionResponse();

  KickConnectionResponse(const KickConnectionResponse& from);
  KickConnectionResponse(KickConnectionResponse&& from) noexcept
    : KickConnectionResponse() {
    *this = ::std::move(from);
  }

  inline KickConnectionResponse& operator=(const KickConnectionResponse& from) {
    CopyFrom(from);
    return *this;
  }
  inline KickConnectionResponse& operator=(KickConnectionResponse&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const KickConnectionResponse& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const KickConnectionResponse* internal_default_instance() {
    return reinterpret_cast<const KickConnectionResponse*>(
               &_KickConnectionResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    4;

  friend void swap(KickConnectionResponse& a, KickConnectionResponse& b) {
    a.Swap(&b);
  }
  inline void Swap(KickConnectionResponse* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(KickConnectionResponse* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline KickConnectionResponse* New() const final {
    return CreateMaybeMessage<KickConnectionResponse>(nullptr);
  }

  KickConnectionResponse* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<KickConnectionResponse>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const KickConnectionResponse& from);
  void MergeFrom(const KickConnectionResponse& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(KickConnectionResponse* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "gwpush.KickConnectionResponse";
  }
  protected:
  explicit KickConnectionResponse(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_gateway_5fpush_2eproto);
    return ::descriptor_table_gateway_5fpush_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kMessageFieldNumber = 2,
    kOkFieldNumber = 1,
    kClosedFieldNumber = 3,
  };
  // string message = 2;
  void clear_message();
  const std::string& message() const;
  void set_message(const std::string& value);
  void set_message(std::string&& value);
  void set_message(const char* value);
  void set_message(const char* value, size_t size);
  std::string* mutable_message();
  std::string* release_message();
  void set_allocated_message(std::string* message);
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  std::string* unsafe_arena_release_message();
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  void unsafe_arena_set_allocated_message(
      std::string* message);
  private:
  const std::string& _internal_message() const;
  void _internal_set_message(const std::string& value);
  std::string* _internal_mutable_message();
  public:

  // bool ok = 1;
  void clear_ok();
  bool ok() const;
  void set_ok(bool value);
  private:
  bool _internal_ok() const;
  void _internal_set_ok(bool value);
  public:

  // bool closed = 3;
  void clear_closed();
  bool closed() const;
  void set_closed(bool value);
  private:
  bool _internal_closed() const;
  void _internal_set_closed(bool value);
  public:

  // @@protoc_insertion_point(class_scope:gwpush.KickConnectionResponse)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr message_;
  bool ok_;
  bool closed_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_gateway_5fpush_2eproto;
};
// ===================================================================

class GatewayPushService_Stub;

class GatewayPushService : public ::PROTOBUF_NAMESPACE_ID::Service {
 protected:
  // This class should be treated as an abstract interface.
  inline GatewayPushService() {};
 public:
  virtual ~GatewayPushService();

  typedef GatewayPushService_Stub Stub;

  static const ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor* descriptor();

  virtual void PushBatch(::PROTOBUF_NAMESPACE_ID::RpcController* controller,
                       const ::gwpush::PushBatchRequest* request,
                       ::gwpush::PushBatchResponse* response,
                       ::google::protobuf::Closure* done);
  virtual void KickConnection(::PROTOBUF_NAMESPACE_ID::RpcController* controller,
                       const ::gwpush::KickConnectionRequest* request,
                       ::gwpush::KickConnectionResponse* response,
                       ::google::protobuf::Closure* done);

  // implements Service ----------------------------------------------

  const ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor* GetDescriptor();
  void CallMethod(const ::PROTOBUF_NAMESPACE_ID::MethodDescriptor* method,
                  ::PROTOBUF_NAMESPACE_ID::RpcController* controller,
                  const ::PROTOBUF_NAMESPACE_ID::Message* request,
                  ::PROTOBUF_NAMESPACE_ID::Message* response,
                  ::google::protobuf::Closure* done);
  const ::PROTOBUF_NAMESPACE_ID::Message& GetRequestPrototype(
    const ::PROTOBUF_NAMESPACE_ID::MethodDescriptor* method) const;
  const ::PROTOBUF_NAMESPACE_ID::Message& GetResponsePrototype(
    const ::PROTOBUF_NAMESPACE_ID::MethodDescriptor* method) const;

 private:
  GOOGLE_DISALLOW_EVIL_CONSTRUCTORS(GatewayPushService);
};

class GatewayPushService_Stub : public GatewayPushService {
 public:
  GatewayPushService_Stub(::PROTOBUF_NAMESPACE_ID::RpcChannel* channel);
  GatewayPushService_Stub(::PROTOBUF_NAMESPACE_ID::RpcChannel* channel,
                   ::PROTOBUF_NAMESPACE_ID::Service::ChannelOwnership ownership);
  ~GatewayPushService_Stub();

  inline ::PROTOBUF_NAMESPACE_ID::RpcChannel* channel() { return channel_; }

  // implements GatewayPushService ------------------------------------------

  void PushBatch(::PROTOBUF_NAMESPACE_ID::RpcController* controller,
                       const ::gwpush::PushBatchRequest* request,
                       ::gwpush::PushBatchResponse* response,
                       ::google::protobuf::Closure* done);
  void KickConnection(::PROTOBUF_NAMESPACE_ID::RpcController* controller,
                       const ::gwpush::KickConnectionRequest* request,
                       ::gwpush::KickConnectionResponse* response,
                       ::google::protobuf::Closure* done);
 private:
  ::PROTOBUF_NAMESPACE_ID::RpcChannel* channel_;
  bool owns_channel_;
  GOOGLE_DISALLOW_EVIL_CONSTRUCTORS(GatewayPushService_Stub);
};


// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// PushMessage

// uint64 player_id = 1;
inline void PushMessage::clear_player_id() {
  player_id_ = PROTOBUF_ULONGLONG(0);
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 PushMessage::_internal_player_id() const {
  return player_id_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 PushMessage::player_id() const {
  // @@protoc_insertion_point(field_get:gwpush.PushMessage.player_id)
  return _internal_player_id();
}
inline void PushMessage::_internal_set_player_id(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  
  player_id_ = value;
}
inline void PushMessage::set_player_id(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  _internal_set_player_id(value);
  // @@protoc_insertion_point(field_set:gwpush.PushMessage.player_id)
}

// string session_id = 2;
inline void PushMessage::clear_session_id() {
  session_id_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline const std::string& PushMessage::session_id() const {
  // @@protoc_insertion_point(field_get:gwpush.PushMessage.session_id)
  return _internal_session_id();
}
inline void PushMessage::set_session_id(const std::string& value) {
  _internal_set_session_id(value);
  // @@protoc_insertion_point(field_set:gwpush.PushMessage.session_id)
}
inline std::string* PushMessage::mutable_session_id() {
  // @@protoc_insertion_point(field_mutable:gwpush.PushMessage.session_id)
  return _internal_mutable_session_id();
}
inline const std::string& PushMessage::_internal_session_id() const {
  return session_id_.Get();
}
inline void PushMessage::_internal_set_session_id(const std::string& value) {
  
  session_id_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value, GetArena());
}
inline void PushMessage::set_session_id(std::string&& value) {
  
  session_id_.Set(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:gwpush.PushMessage.session_id)
}
inline void PushMessage::set_session_id(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  session_id_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value),
              GetArena());
  // @@protoc_insertion_point(field_set_char:gwpush.PushMessage.session_id)
}
inline void PushMessage::set_session_id(const char* value,
    size_t size) {
  
  session_id_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:gwpush.PushMessage.session_id)
}
inline std::string* PushMessage::_internal_mutable_session_id() {
  
  return session_id_.Mutable(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline std::string* PushMessage::release_session_id() {
  // @@protoc_insertion_point(field_release:gwpush.PushMessage.session_id)
  return session_id_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void PushMessage::set_allocated_session_id(std::string* session_id) {
  if (session_id != nullptr) {
    
  } else {
    
  }
  session_id_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), session_id,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:gwpush.PushMessage.session_id)
}
inline std::string* PushMessage::unsafe_arena_release_session_id() {
  // @@protoc_insertion_point(field_unsafe_arena_release:gwpush.PushMessage.session_id)
  GOOGLE_DCHECK(GetArena() != nullptr);
  
  return session_id_.UnsafeArenaRelease(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      GetArena());
}
inline void PushMessage::unsafe_arena_set_allocated_session_id(
    std::string* session_id) {
  GOOGLE_DCHECK(GetArena() != nullptr);
  if (session_id != nullptr) {
    
  } else {
    
  }
  session_id_.UnsafeArenaSetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      session_id, GetArena());
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:gwpush.PushMessage.session_id)
}

// uint64 server_seq = 3;
inline void PushMessage::clear_server_seq() {
  server_seq_ = PROTOBUF_ULONGLONG(0);
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 PushMessage::_internal_server_seq() const {
  return server_seq_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 PushMessage::server_seq() const {
  // @@protoc_insertion_point(field_get:gwpush.PushMessage.server_seq)
  return _internal_server_seq();
}
inline void PushMessage::_internal_set_server_seq(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  
  server_seq_ = value;
}
inline void PushMessage::set_server_seq(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  _internal_set_server_seq(value);
  // @@protoc_insertion_point(field_set:gwpush.PushMessage.server_seq)
}

// string message_type = 4;
inline void PushMessage::clear_message_type() {
  message_type_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline const std::string& PushMessage::message_type() const {
  // @@protoc_insertion_point(field_get:gwpush.PushMessage.message_type)
  return _internal_message_type();
}
inline void PushMessage::set_message_type(const std::string& value) {
  _internal_set_message_type(value);
  // @@protoc_insertion_point(field_set:gwpush.PushMessage.message_type)
}
inline std::string* PushMessage::mutable_message_type() {
  // @@protoc_insertion_point(field_mutable:gwpush.PushMessage.message_type)
  return _internal_mutable_message_type();
}
inline const std::string& PushMessage::_internal_message_type() const {
  return message_type_.Get();
}
inline void PushMessage::_internal_set_message_type(const std::string& value) {
  
  message_type_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value, GetArena());
}
inline void PushMessage::set_message_type(std::string&& value) {
  
  message_type_.Set(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:gwpush.PushMessage.message_type)
}
inline void PushMessage::set_message_type(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  message_type_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value),
              GetArena());
  // @@protoc_insertion_point(field_set_char:gwpush.PushMessage.message_type)
}
inline void PushMessage::set_message_type(const char* value,
    size_t size) {
  
  message_type_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:gwpush.PushMessage.message_type)
}
inline std::string* PushMessage::_internal_mutable_message_type() {
  
  return message_type_.Mutable(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline std::string* PushMessage::release_message_type() {
  // @@protoc_insertion_point(field_release:gwpush.PushMessage.message_type)
  return message_type_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void PushMessage::set_allocated_message_type(std::string* message_type) {
  if (message_type != nullptr) {
    
  } else {
    
  }
  message_type_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), message_type,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:gwpush.PushMessage.message_type)
}
inline std::string* PushMessage::unsafe_arena_release_message_type() {
  // @@protoc_insertion_point(field_unsafe_arena_release:gwpush.PushMessage.message_type)
  GOOGLE_DCHECK(GetArena() != nullptr);
  
  return message_type_.UnsafeArenaRelease(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      GetArena());
}
inline void PushMessage::unsafe_arena_set_allocated_message_type(
    std::string* message_type) {
  GOOGLE_DCHECK(GetArena() != nullptr);
  if (message_type != nullptr) {
    
  } else {
    
  }
  message_type_.UnsafeArenaSetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      message_type, GetArena());
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:gwpush.PushMessage.message_type)
}

// bytes payload = 5;
inline void PushMessage::clear_payload() {
  payload_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline const std::string& PushMessage::payload() const {
  // @@protoc_insertion_point(field_get:gwpush.PushMessage.payload)
  return _internal_payload();
}
inline void PushMessage::set_payload(const std::string& value) {
  _internal_set_payload(value);
  // @@protoc_insertion_point(field_set:gwpush.PushMessage.payload)
}
inline std::string* PushMessage::mutable_payload() {
  // @@protoc_insertion_point(field_mutable:gwpush.PushMessage.payload)
  return _internal_mutable_payload();
}
inline const std::string& PushMessage::_internal_payload() const {
  return payload_.Get();
}
inline void PushMessage::_internal_set_payload(const std::string& value) {
  
  payload_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value, GetArena());
}
inline void PushMessage::set_payload(std::string&& value) {
  
  payload_.Set(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:gwpush.PushMessage.payload)
}
inline void PushMessage::set_payload(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  payload_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value),
              GetArena());
  // @@protoc_insertion_point(field_set_char:gwpush.PushMessage.payload)
}
inline void PushMessage::set_payload(const void* value,
    size_t size) {
  
  payload_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:gwpush.PushMessage.payload)
}
inline std::string* PushMessage::_internal_mutable_payload() {
  
  return payload_.Mutable(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline std::string* PushMessage::release_payload() {
  // @@protoc_insertion_point(field_release:gwpush.PushMessage.payload)
  return payload_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void PushMessage::set_allocated_payload(std::string* payload) {
  if (payload != nullptr) {
    
  } else {
    
  }
  payload_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), payload,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:gwpush.PushMessage.payload)
}
inline std::string* PushMessage::unsafe_arena_release_payload() {
  // @@protoc_insertion_point(field_unsafe_arena_release:gwpush.PushMessage.payload)
  GOOGLE_DCHECK(GetArena() != nullptr);
  
  return payload_.UnsafeArenaRelease(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      GetArena());
}
inline void PushMessage::unsafe_arena_set_allocated_payload(
    std::string* payload) {
  GOOGLE_DCHECK(GetArena() != nullptr);
  if (payload != nullptr) {
    
  } else {
    
  }
  payload_.UnsafeArenaSetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      payload, GetArena());
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:gwpush.PushMessage.payload)
}

// bool reliable = 6;
inline void PushMessage::clear_reliable() {
  reliable_ = false;
}
inline bool PushMessage::_internal_reliable() const {
  return reliable_;
}
inline bool PushMessage::reliable() const {
  // @@protoc_insertion_point(field_get:gwpush.PushMessage.reliable)
  return _internal_reliable();
}
inline void PushMessage::_internal_set_reliable(bool value) {
  
  reliable_ = value;
}
inline void PushMessage::set_reliable(bool value) {
  _internal_set_reliable(value);
  // @@protoc_insertion_point(field_set:gwpush.PushMessage.reliable)
}

// bool coalescable = 7;
inline void PushMessage::clear_coalescable() {
  coalescable_ = false;
}
inline bool PushMessage::_internal_coalescable() const {
  return coalescable_;
}
inline bool PushMessage::coalescable() const {
  // @@protoc_insertion_point(field_get:gwpush.PushMessage.coalescable)
  return _internal_coalescable();
}
inline void PushMessage::_internal_set_coalescable(bool value) {
  
  coalescable_ = value;
}
inline void PushMessage::set_coalescable(bool value) {
  _internal_set_coalescable(value);
  // @@protoc_insertion_point(field_set:gwpush.PushMessage.coalescable)
}

// string fence_token = 8;
inline void PushMessage::clear_fence_token() {
  fence_token_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline const std::string& PushMessage::fence_token() const {
  // @@protoc_insertion_point(field_get:gwpush.PushMessage.fence_token)
  return _internal_fence_token();
}
inline void PushMessage::set_fence_token(const std::string& value) {
  _internal_set_fence_token(value);
  // @@protoc_insertion_point(field_set:gwpush.PushMessage.fence_token)
}
inline std::string* PushMessage::mutable_fence_token() {
  // @@protoc_insertion_point(field_mutable:gwpush.PushMessage.fence_token)
  return _internal_mutable_fence_token();
}
inline const std::string& PushMessage::_internal_fence_token() const {
  return fence_token_.Get();
}
inline void PushMessage::_internal_set_fence_token(const std::string& value) {
  
  fence_token_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value, GetArena());
}
inline void PushMessage::set_fence_token(std::string&& value) {
  
  fence_token_.Set(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:gwpush.PushMessage.fence_token)
}
inline void PushMessage::set_fence_token(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  fence_token_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value),
              GetArena());
  // @@protoc_insertion_point(field_set_char:gwpush.PushMessage.fence_token)
}
inline void PushMessage::set_fence_token(const char* value,
    size_t size) {
  
  fence_token_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:gwpush.PushMessage.fence_token)
}
inline std::string* PushMessage::_internal_mutable_fence_token() {
  
  return fence_token_.Mutable(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline std::string* PushMessage::release_fence_token() {
  // @@protoc_insertion_point(field_release:gwpush.PushMessage.fence_token)
  return fence_token_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void PushMessage::set_allocated_fence_token(std::string* fence_token) {
  if (fence_token != nullptr) {
    
  } else {
    
  }
  fence_token_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), fence_token,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:gwpush.PushMessage.fence_token)
}
inline std::string* PushMessage::unsafe_arena_release_fence_token() {
  // @@protoc_insertion_point(field_unsafe_arena_release:gwpush.PushMessage.fence_token)
  GOOGLE_DCHECK(GetArena() != nullptr);
  
  return fence_token_.UnsafeArenaRelease(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      GetArena());
}
inline void PushMessage::unsafe_arena_set_allocated_fence_token(
    std::string* fence_token) {
  GOOGLE_DCHECK(GetArena() != nullptr);
  if (fence_token != nullptr) {
    
  } else {
    
  }
  fence_token_.UnsafeArenaSetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      fence_token, GetArena());
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:gwpush.PushMessage.fence_token)
}

// uint64 generation = 9;
inline void PushMessage::clear_generation() {
  generation_ = PROTOBUF_ULONGLONG(0);
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 PushMessage::_internal_generation() const {
  return generation_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 PushMessage::generation() const {
  // @@protoc_insertion_point(field_get:gwpush.PushMessage.generation)
  return _internal_generation();
}
inline void PushMessage::_internal_set_generation(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  
  generation_ = value;
}
inline void PushMessage::set_generation(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  _internal_set_generation(value);
  // @@protoc_insertion_point(field_set:gwpush.PushMessage.generation)
}

// -------------------------------------------------------------------

// PushBatchRequest

// string gateway_instance_id = 1;
inline void PushBatchRequest::clear_gateway_instance_id() {
  gateway_instance_id_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline const std::string& PushBatchRequest::gateway_instance_id() const {
  // @@protoc_insertion_point(field_get:gwpush.PushBatchRequest.gateway_instance_id)
  return _internal_gateway_instance_id();
}
inline void PushBatchRequest::set_gateway_instance_id(const std::string& value) {
  _internal_set_gateway_instance_id(value);
  // @@protoc_insertion_point(field_set:gwpush.PushBatchRequest.gateway_instance_id)
}
inline std::string* PushBatchRequest::mutable_gateway_instance_id() {
  // @@protoc_insertion_point(field_mutable:gwpush.PushBatchRequest.gateway_instance_id)
  return _internal_mutable_gateway_instance_id();
}
inline const std::string& PushBatchRequest::_internal_gateway_instance_id() const {
  return gateway_instance_id_.Get();
}
inline void PushBatchRequest::_internal_set_gateway_instance_id(const std::string& value) {
  
  gateway_instance_id_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value, GetArena());
}
inline void PushBatchRequest::set_gateway_instance_id(std::string&& value) {
  
  gateway_instance_id_.Set(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:gwpush.PushBatchRequest.gateway_instance_id)
}
inline void PushBatchRequest::set_gateway_instance_id(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  gateway_instance_id_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value),
              GetArena());
  // @@protoc_insertion_point(field_set_char:gwpush.PushBatchRequest.gateway_instance_id)
}
inline void PushBatchRequest::set_gateway_instance_id(const char* value,
    size_t size) {
  
  gateway_instance_id_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:gwpush.PushBatchRequest.gateway_instance_id)
}
inline std::string* PushBatchRequest::_internal_mutable_gateway_instance_id() {
  
  return gateway_instance_id_.Mutable(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline std::string* PushBatchRequest::release_gateway_instance_id() {
  // @@protoc_insertion_point(field_release:gwpush.PushBatchRequest.gateway_instance_id)
  return gateway_instance_id_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void PushBatchRequest::set_allocated_gateway_instance_id(std::string* gateway_instance_id) {
  if (gateway_instance_id != nullptr) {
    
  } else {
    
  }
  gateway_instance_id_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), gateway_instance_id,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:gwpush.PushBatchRequest.gateway_instance_id)
}
inline std::string* PushBatchRequest::unsafe_arena_release_gateway_instance_id() {
  // @@protoc_insertion_point(field_unsafe_arena_release:gwpush.PushBatchRequest.gateway_instance_id)
  GOOGLE_DCHECK(GetArena() != nullptr);
  
  return gateway_instance_id_.UnsafeArenaRelease(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      GetArena());
}
inline void PushBatchRequest::unsafe_arena_set_allocated_gateway_instance_id(
    std::string* gateway_instance_id) {
  GOOGLE_DCHECK(GetArena() != nullptr);
  if (gateway_instance_id != nullptr) {
    
  } else {
    
  }
  gateway_instance_id_.UnsafeArenaSetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      gateway_instance_id, GetArena());
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:gwpush.PushBatchRequest.gateway_instance_id)
}

// repeated .gwpush.PushMessage messages = 2;
inline int PushBatchRequest::_internal_messages_size() const {
  return messages_.size();
}
inline int PushBatchRequest::messages_size() const {
  return _internal_messages_size();
}
inline void PushBatchRequest::clear_messages() {
  messages_.Clear();
}
inline ::gwpush::PushMessage* PushBatchRequest::mutable_messages(int index) {
  // @@protoc_insertion_point(field_mutable:gwpush.PushBatchRequest.messages)
  return messages_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::gwpush::PushMessage >*
PushBatchRequest::mutable_messages() {
  // @@protoc_insertion_point(field_mutable_list:gwpush.PushBatchRequest.messages)
  return &messages_;
}
inline const ::gwpush::PushMessage& PushBatchRequest::_internal_messages(int index) const {
  return messages_.Get(index);
}
inline const ::gwpush::PushMessage& PushBatchRequest::messages(int index) const {
  // @@protoc_insertion_point(field_get:gwpush.PushBatchRequest.messages)
  return _internal_messages(index);
}
inline ::gwpush::PushMessage* PushBatchRequest::_internal_add_messages() {
  return messages_.Add();
}
inline ::gwpush::PushMessage* PushBatchRequest::add_messages() {
  // @@protoc_insertion_point(field_add:gwpush.PushBatchRequest.messages)
  return _internal_add_messages();
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::gwpush::PushMessage >&
PushBatchRequest::messages() const {
  // @@protoc_insertion_point(field_list:gwpush.PushBatchRequest.messages)
  return messages_;
}

// -------------------------------------------------------------------

// PushBatchResponse

// bool ok = 1;
inline void PushBatchResponse::clear_ok() {
  ok_ = false;
}
inline bool PushBatchResponse::_internal_ok() const {
  return ok_;
}
inline bool PushBatchResponse::ok() const {
  // @@protoc_insertion_point(field_get:gwpush.PushBatchResponse.ok)
  return _internal_ok();
}
inline void PushBatchResponse::_internal_set_ok(bool value) {
  
  ok_ = value;
}
inline void PushBatchResponse::set_ok(bool value) {
  _internal_set_ok(value);
  // @@protoc_insertion_point(field_set:gwpush.PushBatchResponse.ok)
}

// string message = 2;
inline void PushBatchResponse::clear_message() {
  message_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline const std::string& PushBatchResponse::message() const {
  // @@protoc_insertion_point(field_get:gwpush.PushBatchResponse.message)
  return _internal_message();
}
inline void PushBatchResponse::set_message(const std::string& value) {
  _internal_set_message(value);
  // @@protoc_insertion_point(field_set:gwpush.PushBatchResponse.message)
}
inline std::string* PushBatchResponse::mutable_message() {
  // @@protoc_insertion_point(field_mutable:gwpush.PushBatchResponse.message)
  return _internal_mutable_message();
}
inline const std::string& PushBatchResponse::_internal_message() const {
  return message_.Get();
}
inline void PushBatchResponse::_internal_set_message(const std::string& value) {
  
  message_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value, GetArena());
}
inline void PushBatchResponse::set_message(std::string&& value) {
  
  message_.Set(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:gwpush.PushBatchResponse.message)
}
inline void PushBatchResponse::set_message(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  message_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value),
              GetArena());
  // @@protoc_insertion_point(field_set_char:gwpush.PushBatchResponse.message)
}
inline void PushBatchResponse::set_message(const char* value,
    size_t size) {
  
  message_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:gwpush.PushBatchResponse.message)
}
inline std::string* PushBatchResponse::_internal_mutable_message() {
  
  return message_.Mutable(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline std::string* PushBatchResponse::release_message() {
  // @@protoc_insertion_point(field_release:gwpush.PushBatchResponse.message)
  return message_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void PushBatchResponse::set_allocated_message(std::string* message) {
  if (message != nullptr) {
    
  } else {
    
  }
  message_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), message,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:gwpush.PushBatchResponse.message)
}
inline std::string* PushBatchResponse::unsafe_arena_release_message() {
  // @@protoc_insertion_point(field_unsafe_arena_release:gwpush.PushBatchResponse.message)
  GOOGLE_DCHECK(GetArena() != nullptr);
  
  return message_.UnsafeArenaRelease(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      GetArena());
}
inline void PushBatchResponse::unsafe_arena_set_allocated_message(
    std::string* message) {
  GOOGLE_DCHECK(GetArena() != nullptr);
  if (message != nullptr) {
    
  } else {
    
  }
  message_.UnsafeArenaSetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      message, GetArena());
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:gwpush.PushBatchResponse.message)
}

// uint32 accepted = 3;
inline void PushBatchResponse::clear_accepted() {
  accepted_ = 0u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 PushBatchResponse::_internal_accepted() const {
  return accepted_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 PushBatchResponse::accepted() const {
  // @@protoc_insertion_point(field_get:gwpush.PushBatchResponse.accepted)
  return _internal_accepted();
}
inline void PushBatchResponse::_internal_set_accepted(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  
  accepted_ = value;
}
inline void PushBatchResponse::set_accepted(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _internal_set_accepted(value);
  // @@protoc_insertion_point(field_set:gwpush.PushBatchResponse.accepted)
}

// uint32 rejected = 4;
inline void PushBatchResponse::clear_rejected() {
  rejected_ = 0u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 PushBatchResponse::_internal_rejected() const {
  return rejected_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 PushBatchResponse::rejected() const {
  // @@protoc_insertion_point(field_get:gwpush.PushBatchResponse.rejected)
  return _internal_rejected();
}
inline void PushBatchResponse::_internal_set_rejected(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  
  rejected_ = value;
}
inline void PushBatchResponse::set_rejected(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _internal_set_rejected(value);
  // @@protoc_insertion_point(field_set:gwpush.PushBatchResponse.rejected)
}

// -------------------------------------------------------------------

// KickConnectionRequest

// uint64 player_id = 1;
inline void KickConnectionRequest::clear_player_id() {
  player_id_ = PROTOBUF_ULONGLONG(0);
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 KickConnectionRequest::_internal_player_id() const {
  return player_id_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 KickConnectionRequest::player_id() const {
  // @@protoc_insertion_point(field_get:gwpush.KickConnectionRequest.player_id)
  return _internal_player_id();
}
inline void KickConnectionRequest::_internal_set_player_id(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  
  player_id_ = value;
}
inline void KickConnectionRequest::set_player_id(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  _internal_set_player_id(value);
  // @@protoc_insertion_point(field_set:gwpush.KickConnectionRequest.player_id)
}

// string session_id = 2;
inline void KickConnectionRequest::clear_session_id() {
  session_id_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline const std::string& KickConnectionRequest::session_id() const {
  // @@protoc_insertion_point(field_get:gwpush.KickConnectionRequest.session_id)
  return _internal_session_id();
}
inline void KickConnectionRequest::set_session_id(const std::string& value) {
  _internal_set_session_id(value);
  // @@protoc_insertion_point(field_set:gwpush.KickConnectionRequest.session_id)
}
inline std::string* KickConnectionRequest::mutable_session_id() {
  // @@protoc_insertion_point(field_mutable:gwpush.KickConnectionRequest.session_id)
  return _internal_mutable_session_id();
}
inline const std::string& KickConnectionRequest::_internal_session_id() const {
  return session_id_.Get();
}
inline void KickConnectionRequest::_internal_set_session_id(const std::string& value) {
  
  session_id_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value, GetArena());
}
inline void KickConnectionRequest::set_session_id(std::string&& value) {
  
  session_id_.Set(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:gwpush.KickConnectionRequest.session_id)
}
inline void KickConnectionRequest::set_session_id(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  session_id_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value),
              GetArena());
  // @@protoc_insertion_point(field_set_char:gwpush.KickConnectionRequest.session_id)
}
inline void KickConnectionRequest::set_session_id(const char* value,
    size_t size) {
  
  session_id_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:gwpush.KickConnectionRequest.session_id)
}
inline std::string* KickConnectionRequest::_internal_mutable_session_id() {
  
  return session_id_.Mutable(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline std::string* KickConnectionRequest::release_session_id() {
  // @@protoc_insertion_point(field_release:gwpush.KickConnectionRequest.session_id)
  return session_id_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void KickConnectionRequest::set_allocated_session_id(std::string* session_id) {
  if (session_id != nullptr) {
    
  } else {
    
  }
  session_id_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), session_id,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:gwpush.KickConnectionRequest.session_id)
}
inline std::string* KickConnectionRequest::unsafe_arena_release_session_id() {
  // @@protoc_insertion_point(field_unsafe_arena_release:gwpush.KickConnectionRequest.session_id)
  GOOGLE_DCHECK(GetArena() != nullptr);
  
  return session_id_.UnsafeArenaRelease(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      GetArena());
}
inline void KickConnectionRequest::unsafe_arena_set_allocated_session_id(
    std::string* session_id) {
  GOOGLE_DCHECK(GetArena() != nullptr);
  if (session_id != nullptr) {
    
  } else {
    
  }
  session_id_.UnsafeArenaSetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      session_id, GetArena());
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:gwpush.KickConnectionRequest.session_id)
}

// uint64 generation = 3;
inline void KickConnectionRequest::clear_generation() {
  generation_ = PROTOBUF_ULONGLONG(0);
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 KickConnectionRequest::_internal_generation() const {
  return generation_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 KickConnectionRequest::generation() const {
  // @@protoc_insertion_point(field_get:gwpush.KickConnectionRequest.generation)
  return _internal_generation();
}
inline void KickConnectionRequest::_internal_set_generation(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  
  generation_ = value;
}
inline void KickConnectionRequest::set_generation(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  _internal_set_generation(value);
  // @@protoc_insertion_point(field_set:gwpush.KickConnectionRequest.generation)
}

// string reason = 4;
inline void KickConnectionRequest::clear_reason() {
  reason_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline const std::string& KickConnectionRequest::reason() const {
  // @@protoc_insertion_point(field_get:gwpush.KickConnectionRequest.reason)
  return _internal_reason();
}
inline void KickConnectionRequest::set_reason(const std::string& value) {
  _internal_set_reason(value);
  // @@protoc_insertion_point(field_set:gwpush.KickConnectionRequest.reason)
}
inline std::string* KickConnectionRequest::mutable_reason() {
  // @@protoc_insertion_point(field_mutable:gwpush.KickConnectionRequest.reason)
  return _internal_mutable_reason();
}
inline const std::string& KickConnectionRequest::_internal_reason() const {
  return reason_.Get();
}
inline void KickConnectionRequest::_internal_set_reason(const std::string& value) {
  
  reason_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value, GetArena());
}
inline void KickConnectionRequest::set_reason(std::string&& value) {
  
  reason_.Set(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:gwpush.KickConnectionRequest.reason)
}
inline void KickConnectionRequest::set_reason(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  reason_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value),
              GetArena());
  // @@protoc_insertion_point(field_set_char:gwpush.KickConnectionRequest.reason)
}
inline void KickConnectionRequest::set_reason(const char* value,
    size_t size) {
  
  reason_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:gwpush.KickConnectionRequest.reason)
}
inline std::string* KickConnectionRequest::_internal_mutable_reason() {
  
  return reason_.Mutable(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline std::string* KickConnectionRequest::release_reason() {
  // @@protoc_insertion_point(field_release:gwpush.KickConnectionRequest.reason)
  return reason_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void KickConnectionRequest::set_allocated_reason(std::string* reason) {
  if (reason != nullptr) {
    
  } else {
    
  }
  reason_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), reason,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:gwpush.KickConnectionRequest.reason)
}
inline std::string* KickConnectionRequest::unsafe_arena_release_reason() {
  // @@protoc_insertion_point(field_unsafe_arena_release:gwpush.KickConnectionRequest.reason)
  GOOGLE_DCHECK(GetArena() != nullptr);
  
  return reason_.UnsafeArenaRelease(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      GetArena());
}
inline void KickConnectionRequest::unsafe_arena_set_allocated_reason(
    std::string* reason) {
  GOOGLE_DCHECK(GetArena() != nullptr);
  if (reason != nullptr) {
    
  } else {
    
  }
  reason_.UnsafeArenaSetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      reason, GetArena());
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:gwpush.KickConnectionRequest.reason)
}

// -------------------------------------------------------------------

// KickConnectionResponse

// bool ok = 1;
inline void KickConnectionResponse::clear_ok() {
  ok_ = false;
}
inline bool KickConnectionResponse::_internal_ok() const {
  return ok_;
}
inline bool KickConnectionResponse::ok() const {
  // @@protoc_insertion_point(field_get:gwpush.KickConnectionResponse.ok)
  return _internal_ok();
}
inline void KickConnectionResponse::_internal_set_ok(bool value) {
  
  ok_ = value;
}
inline void KickConnectionResponse::set_ok(bool value) {
  _internal_set_ok(value);
  // @@protoc_insertion_point(field_set:gwpush.KickConnectionResponse.ok)
}

// string message = 2;
inline void KickConnectionResponse::clear_message() {
  message_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline const std::string& KickConnectionResponse::message() const {
  // @@protoc_insertion_point(field_get:gwpush.KickConnectionResponse.message)
  return _internal_message();
}
inline void KickConnectionResponse::set_message(const std::string& value) {
  _internal_set_message(value);
  // @@protoc_insertion_point(field_set:gwpush.KickConnectionResponse.message)
}
inline std::string* KickConnectionResponse::mutable_message() {
  // @@protoc_insertion_point(field_mutable:gwpush.KickConnectionResponse.message)
  return _internal_mutable_message();
}
inline const std::string& KickConnectionResponse::_internal_message() const {
  return message_.Get();
}
inline void KickConnectionResponse::_internal_set_message(const std::string& value) {
  
  message_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value, GetArena());
}
inline void KickConnectionResponse::set_message(std::string&& value) {
  
  message_.Set(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:gwpush.KickConnectionResponse.message)
}
inline void KickConnectionResponse::set_message(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  message_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value),
              GetArena());
  // @@protoc_insertion_point(field_set_char:gwpush.KickConnectionResponse.message)
}
inline void KickConnectionResponse::set_message(const char* value,
    size_t size) {
  
  message_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:gwpush.KickConnectionResponse.message)
}
inline std::string* KickConnectionResponse::_internal_mutable_message() {
  
  return message_.Mutable(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline std::string* KickConnectionResponse::release_message() {
  // @@protoc_insertion_point(field_release:gwpush.KickConnectionResponse.message)
  return message_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void KickConnectionResponse::set_allocated_message(std::string* message) {
  if (message != nullptr) {
    
  } else {
    
  }
  message_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), message,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:gwpush.KickConnectionResponse.message)
}
inline std::string* KickConnectionResponse::unsafe_arena_release_message() {
  // @@protoc_insertion_point(field_unsafe_arena_release:gwpush.KickConnectionResponse.message)
  GOOGLE_DCHECK(GetArena() != nullptr);
  
  return message_.UnsafeArenaRelease(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      GetArena());
}
inline void KickConnectionResponse::unsafe_arena_set_allocated_message(
    std::string* message) {
  GOOGLE_DCHECK(GetArena() != nullptr);
  if (message != nullptr) {
    
  } else {
    
  }
  message_.UnsafeArenaSetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      message, GetArena());
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:gwpush.KickConnectionResponse.message)
}

// bool closed = 3;
inline void KickConnectionResponse::clear_closed() {
  closed_ = false;
}
inline bool KickConnectionResponse::_internal_closed() const {
  return closed_;
}
inline bool KickConnectionResponse::closed() const {
  // @@protoc_insertion_point(field_get:gwpush.KickConnectionResponse.closed)
  return _internal_closed();
}
inline void KickConnectionResponse::_internal_set_closed(bool value) {
  
  closed_ = value;
}
inline void KickConnectionResponse::set_closed(bool value) {
  _internal_set_closed(value);
  // @@protoc_insertion_point(field_set:gwpush.KickConnectionResponse.closed)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace gwpush

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_gateway_5fpush_2eproto
