// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: gateway_push.proto

#include "gateway_push.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// This is a temporary google only hack
#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
#include "third_party/protobuf/version.h"
#endif
// @@protoc_insertion_point(includes)
namespace gwpush {
class PushMessageDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<PushMessage>
      _instance;
} _PushMessage_default_instance_;
class PushBatchRequestDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<PushBatchRequest>
      _instance;
} _PushBatchRequest_default_instance_;
class PushBatchResponseDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<PushBatchResponse>
      _instance;
} _PushBatchResponse_default_instance_;
}  // namespace gwpush
namespace protobuf_gateway_5fpush_2eproto {
void InitDefaultsPushMessageImpl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  ::google::protobuf::internal::InitProtobufDefaultsForceUnique();
#else
  ::google::protobuf::internal::InitProtobufDefaults();
#endif  // GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  {
    void* ptr = &::gwpush::_PushMessage_default_instance_;
    new (ptr) ::gwpush::PushMessage();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::gwpush::PushMessage::InitAsDefaultInstance();
}

void InitDefaultsPushMessage() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &InitDefaultsPushMessageImpl);
}

void InitDefaultsPushBatchRequestImpl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  ::google::protobuf::internal::InitProtobufDefaultsForceUnique();
#else
  ::google::protobuf::internal::InitProtobufDefaults();
#endif  // GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  protobuf_gateway_5fpush_2eproto::InitDefaultsPushMessage();
  {
    void* ptr = &::gwpush::_PushBatchRequest_default_instance_;
    new (ptr) ::gwpush::PushBatchRequest();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::gwpush::PushBatchRequest::InitAsDefaultInstance();
}

void InitDefaultsPushBatchRequest() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &InitDefaultsPushBatchRequestImpl);
}

void InitDefaultsPushBatchResponseImpl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  ::google::protobuf::internal::InitProtobufDefaultsForceUnique();
#else
  ::google::protobuf::internal::InitProtobufDefaults();
#endif  // GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  {
    void* ptr = &::gwpush::_PushBatchResponse_default_instance_;
    new (ptr) ::gwpush::PushBatchResponse();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::gwpush::PushBatchResponse::InitAsDefaultInstance();
}

void InitDefaultsPushBatchResponse() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &InitDefaultsPushBatchResponseImpl);
}

::google::protobuf::Metadata file_level_metadata[3];
const ::google::protobuf::ServiceDescriptor* file_level_service_descriptors[1];

const ::google::protobuf::uint32 TableStruct::offsets[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::gwpush::PushMessage, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::gwpush::PushMessage, player_id_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::gwpush::PushMessage, session_id_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::gwpush::PushMessage, server_seq_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::gwpush::PushMessage, message_type_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::gwpush::PushMessage, payload_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::gwpush::PushMessage, reliable_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::gwpush::PushMessage, coalescable_),
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::gwpush::PushBatchRequest, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::gwpush::PushBatchRequest, gateway_instance_id_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::gwpush::PushBatchRequest, messages_),
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::gwpush::PushBatchResponse, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::gwpush::PushBatchResponse, ok_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::gwpush::PushBatchResponse, message_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::gwpush::PushBatchResponse, accepted_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::gwpush::PushBatchResponse, rejected_),
};
static const ::google::protobuf::internal::MigrationSchema schemas[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::gwpush::PushMessage)},
  { 12, -1, sizeof(::gwpush::PushBatchRequest)},
  { 19, -1, sizeof(::gwpush::PushBatchResponse)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&::gwpush::_PushMessage_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::gwpush::_PushBatchRequest_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::gwpush::_PushBatchResponse_default_instance_),
};

void protobuf_AssignDescriptors() {
  AddDescriptors();
  ::google::protobuf::MessageFactory* factory = NULL;
  AssignDescriptors(
      "gateway_push.proto", schemas, file_default_instances, TableStruct::offsets, factory,
      file_level_metadata, NULL, file_level_service_descriptors);
}

void protobuf_AssignDescriptorsOnce() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_PROTOBUF_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 3);
}

void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
      "\n\022gateway_push.proto\022\006gwpush\"\226\001\n\013PushMes"
      "sage\022\021\n\tplayer_id\030\001 \001(\004\022\022\n\nsession_id\030\002 "
      "\001(\t\022\022\n\nserver_seq\030\003 \001(\004\022\024\n\014message_type\030"
      "\004 \001(\t\022\017\n\007payload\030\005 \001(\014\022\020\n\010reliable\030\006 \001(\010"
      "\022\023\n\013coalescable\030\007 \001(\010\"V\n\020PushBatchReques"
      "t\022\033\n\023gateway_instance_id\030\001 \001(\t\022%\n\010messag"
      "es\030\002 \003(\0132\023.gwpush.PushMessage\"T\n\021PushBat"
      "chResponse\022\n\n\002ok\030\001 \001(\010\022\017\n\007message\030\002 \001(\t\022"
      "\020\n\010accepted\030\003 \001(\r\022\020\n\010rejected\030\004 \001(\r2V\n\022G"
      "atewayPushService\022@\n\tPushBatch\022\030.gwpush."
      "PushBatchRequest\032\031.gwpush.PushBatchRespo"
      "nseB\003\200\001\001b\006proto3"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 456);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "gateway_push.proto", &protobuf_RegisterTypes);
}

void AddDescriptors() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at dynamic initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;
}  // namespace protobuf_gateway_5fpush_2eproto
namespace gwpush {

// ===================================================================

void PushMessage::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int PushMessage::kPlayerIdFieldNumber;
const int PushMessage::kSessionIdFieldNumber;
const int PushMessage::kServerSeqFieldNumber;
const int PushMessage::kMessageTypeFieldNumber;
const int PushMessage::kPayloadFieldNumber;
const int PushMessage::kReliableFieldNumber;
const int PushMessage::kCoalescableFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

PushMessage::PushMessage()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    ::protobuf_gateway_5fpush_2eproto::InitDefaultsPushMessage();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:gwpush.PushMessage)
}
PushMessage::PushMessage(const PushMessage& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  session_id_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.session_id().size() > 0) {
    session_id_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.session_id_);
  }
  message_type_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.message_type().size() > 0) {
    message_type_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.message_type_);
  }
  payload_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.payload().size() > 0) {
    payload_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.payload_);
  }
  ::memcpy(&player_id_, &from.player_id_,
    static_cast<size_t>(reinterpret_cast<char*>(&coalescable_) -
    reinterpret_cast<char*>(&player_id_)) + sizeof(coalescable_));
  // @@protoc_insertion_point(copy_constructor:gwpush.PushMessage)
}

void PushMessage::SharedCtor() {
  session_id_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  message_type_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  payload_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::memset(&player_id_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&coalescable_) -
      reinterpret_cast<char*>(&player_id_)) + sizeof(coalescable_));
  _cached_size_ = 0;
}

PushMessage::~PushMessage() {
  // @@protoc_insertion_point(destructor:gwpush.PushMessage)
  SharedDtor();
}

void PushMessage::SharedDtor() {
  session_id_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  message_type_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  payload_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void PushMessage::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* PushMessage::descriptor() {
  ::protobuf_gateway_5fpush_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_gateway_5fpush_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const PushMessage& PushMessage::default_instance() {
  ::protobuf_gateway_5fpush_2eproto::InitDefaultsPushMessage();
  return *internal_default_instance();
}

PushMessage* PushMessage::New(::google::protobuf::Arena* arena) const {
  PushMessage* n = new PushMessage;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void PushMessage::Clear() {
// @@protoc_insertion_point(message_clear_start:gwpush.PushMessage)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  session_id_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  message_type_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  payload_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::memset(&player_id_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&coalescable_) -
      reinterpret_cast<char*>(&player_id_)) + sizeof(coalescable_));
  _internal_metadata_.Clear();
}

bool PushMessage::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:gwpush.PushMessage)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // uint64 player_id = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(8u /* 8 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint64, ::google::protobuf::internal::WireFormatLite::TYPE_UINT64>(
                 input, &player_id_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string session_id = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(18u /* 18 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_session_id()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->session_id().data(), static_cast<int>(this->session_id().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "gwpush.PushMessage.session_id"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // uint64 server_seq = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(24u /* 24 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint64, ::google::protobuf::internal::WireFormatLite::TYPE_UINT64>(
                 input, &server_seq_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string message_type = 4;
      case 4: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(34u /* 34 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_message_type()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->message_type().data(), static_cast<int>(this->message_type().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "gwpush.PushMessage.message_type"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // bytes payload = 5;
      case 5: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(42u /* 42 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadBytes(
                input, this->mutable_payload()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // bool reliable = 6;
      case 6: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(48u /* 48 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 input, &reliable_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // bool coalescable = 7;
      case 7: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(56u /* 56 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 input, &coalescable_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:gwpush.PushMessage)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:gwpush.PushMessage)
  return false;
#undef DO_
}

void PushMessage::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:gwpush.PushMessage)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // uint64 player_id = 1;
  if (this->player_id() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt64(1, this->player_id(), output);
  }

  // string session_id = 2;
  if (this->session_id().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->session_id().data(), static_cast<int>(this->session_id().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "gwpush.PushMessage.session_id");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      2, this->session_id(), output);
  }

  // uint64 server_seq = 3;
  if (this->server_seq() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt64(3, this->server_seq(), output);
  }

  // string message_type = 4;
  if (this->message_type().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->message_type().data(), static_cast<int>(this->message_type().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "gwpush.PushMessage.message_type");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      4, this->message_type(), output);
  }

  // bytes payload = 5;
  if (this->payload().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::WriteBytesMaybeAliased(
      5, this->payload(), output);
  }

  // bool reliable = 6;
  if (this->reliable() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteBool(6, this->reliable(), output);
  }

  // bool coalescable = 7;
  if (this->coalescable() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteBool(7, this->coalescable(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:gwpush.PushMessage)
}

::google::protobuf::uint8* PushMessage::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:gwpush.PushMessage)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // uint64 player_id = 1;
  if (this->player_id() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt64ToArray(1, this->player_id(), target);
  }

  // string session_id = 2;
  if (this->session_id().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->session_id().data(), static_cast<int>(this->session_id().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "gwpush.PushMessage.session_id");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        2, this->session_id(), target);
  }

  // uint64 server_seq = 3;
  if (this->server_seq() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt64ToArray(3, this->server_seq(), target);
  }

  // string message_type = 4;
  if (this->message_type().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->message_type().data(), static_cast<int>(this->message_type().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "gwpush.PushMessage.message_type");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        4, this->message_type(), target);
  }

  // bytes payload = 5;
  if (this->payload().size() > 0) {
    target =
      ::google::protobuf::internal::WireFormatLite::WriteBytesToArray(
        5, this->payload(), target);
  }

  // bool reliable = 6;
  if (this->reliable() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteBoolToArray(6, this->reliable(), target);
  }

  // bool coalescable = 7;
  if (this->coalescable() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteBoolToArray(7, this->coalescable(), target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:gwpush.PushMessage)
  return target;
}

size_t PushMessage::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:gwpush.PushMessage)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // string session_id = 2;
  if (this->session_id().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->session_id());
  }

  // string message_type = 4;
  if (this->message_type().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->message_type());
  }

  // bytes payload = 5;
  if (this->payload().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::BytesSize(
        this->payload());
  }

  // uint64 player_id = 1;
  if (this->player_id() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt64Size(
        this->player_id());
  }

  // uint64 server_seq = 3;
  if (this->server_seq() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt64Size(
        this->server_seq());
  }

  // bool reliable = 6;
  if (this->reliable() != 0) {
    total_size += 1 + 1;
  }

  // bool coalescable = 7;
  if (this->coalescable() != 0) {
    total_size += 1 + 1;
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void PushMessage::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:gwpush.PushMessage)
  GOOGLE_DCHECK_NE(&from, this);
  const PushMessage* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const PushMessage>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:gwpush.PushMessage)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:gwpush.PushMessage)
    MergeFrom(*source);
  }
}

void PushMessage::MergeFrom(const PushMessage& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:gwpush.PushMessage)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.session_id().size() > 0) {

    session_id_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.session_id_);
  }
  if (from.message_type().size() > 0) {

    message_type_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.message_type_);
  }
  if (from.payload().size() > 0) {

    payload_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.payload_);
  }
  if (from.player_id() != 0) {
    set_player_id(from.player_id());
  }
  if (from.server_seq() != 0) {
    set_server_seq(from.server_seq());
  }
  if (from.reliable() != 0) {
    set_reliable(from.reliable());
  }
  if (from.coalescable() != 0) {
    set_coalescable(from.coalescable());
  }
}

void PushMessage::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:gwpush.PushMessage)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void PushMessage::CopyFrom(const PushMessage& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:gwpush.PushMessage)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool PushMessage::IsInitialized() const {
  return true;
}

void PushMessage::Swap(PushMessage* other) {
  if (other == this) return;
  InternalSwap(other);
}
void PushMessage::InternalSwap(PushMessage* other) {
  using std::swap;
  session_id_.Swap(&other->session_id_);
  message_type_.Swap(&other->message_type_);
  payload_.Swap(&other->payload_);
  swap(player_id_, other->player_id_);
  swap(server_seq_, other->server_seq_);
  swap(reliable_, other->reliable_);
  swap(coalescable_, other->coalescable_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata PushMessage::GetMetadata() const {
  protobuf_gateway_5fpush_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_gateway_5fpush_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

void PushBatchRequest::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int PushBatchRequest::kGatewayInstanceIdFieldNumber;
const int PushBatchRequest::kMessagesFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

PushBatchRequest::PushBatchRequest()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    ::protobuf_gateway_5fpush_2eproto::InitDefaultsPushBatchRequest();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:gwpush.PushBatchRequest)
}
PushBatchRequest::PushBatchRequest(const PushBatchRequest& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      messages_(from.messages_),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  gateway_instance_id_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.gateway_instance_id().size() > 0) {
    gateway_instance_id_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.gateway_instance_id_);
  }
  // @@protoc_insertion_point(copy_constructor:gwpush.PushBatchRequest)
}

void PushBatchRequest::SharedCtor() {
  gateway_instance_id_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  _cached_size_ = 0;
}

PushBatchRequest::~PushBatchRequest() {
  // @@protoc_insertion_point(destructor:gwpush.PushBatchRequest)
  SharedDtor();
}

void PushBatchRequest::SharedDtor() {
  gateway_instance_id_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void PushBatchRequest::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* PushBatchRequest::descriptor() {
  ::protobuf_gateway_5fpush_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_gateway_5fpush_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const PushBatchRequest& PushBatchRequest::default_instance() {
  ::protobuf_gateway_5fpush_2eproto::InitDefaultsPushBatchRequest();
  return *internal_default_instance();
}

PushBatchRequest* PushBatchRequest::New(::google::protobuf::Arena* arena) const {
  PushBatchRequest* n = new PushBatchRequest;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void PushBatchRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:gwpush.PushBatchRequest)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  messages_.Clear();
  gateway_instance_id_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  _internal_metadata_.Clear();
}

bool PushBatchRequest::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:gwpush.PushBatchRequest)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // string gateway_instance_id = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u /* 10 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_gateway_instance_id()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->gateway_instance_id().data(), static_cast<int>(this->gateway_instance_id().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "gwpush.PushBatchRequest.gateway_instance_id"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // repeated .gwpush.PushMessage messages = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(18u /* 18 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(input, add_messages()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:gwpush.PushBatchRequest)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:gwpush.PushBatchRequest)
  return false;
#undef DO_
}

void PushBatchRequest::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:gwpush.PushBatchRequest)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string gateway_instance_id = 1;
  if (this->gateway_instance_id().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->gateway_instance_id().data(), static_cast<int>(this->gateway_instance_id().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "gwpush.PushBatchRequest.gateway_instance_id");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      1, this->gateway_instance_id(), output);
  }

  // repeated .gwpush.PushMessage messages = 2;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->messages_size()); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      2, this->messages(static_cast<int>(i)), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:gwpush.PushBatchRequest)
}

::google::protobuf::uint8* PushBatchRequest::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:gwpush.PushBatchRequest)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string gateway_instance_id = 1;
  if (this->gateway_instance_id().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->gateway_instance_id().data(), static_cast<int>(this->gateway_instance_id().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "gwpush.PushBatchRequest.gateway_instance_id");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->gateway_instance_id(), target);
  }

  // repeated .gwpush.PushMessage messages = 2;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->messages_size()); i < n; i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageToArray(
        2, this->messages(static_cast<int>(i)), deterministic, target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:gwpush.PushBatchRequest)
  return target;
}

size_t PushBatchRequest::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:gwpush.PushBatchRequest)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // repeated .gwpush.PushMessage messages = 2;
  {
    unsigned int count = static_cast<unsigned int>(this->messages_size());
    total_size += 1UL * count;
    for (unsigned int i = 0; i < count; i++) {
      total_size +=
        ::google::protobuf::internal::WireFormatLite::MessageSize(
          this->messages(static_cast<int>(i)));
    }
  }

  // string gateway_instance_id = 1;
  if (this->gateway_instance_id().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->gateway_instance_id());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void PushBatchRequest::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:gwpush.PushBatchRequest)
  GOOGLE_DCHECK_NE(&from, this);
  const PushBatchRequest* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const PushBatchRequest>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:gwpush.PushBatchRequest)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:gwpush.PushBatchRequest)
    MergeFrom(*source);
  }
}

void PushBatchRequest::MergeFrom(const PushBatchRequest& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:gwpush.PushBatchRequest)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  messages_.MergeFrom(from.messages_);
  if (from.gateway_instance_id().size() > 0) {

    gateway_instance_id_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.gateway_instance_id_);
  }
}

void PushBatchRequest::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:gwpush.PushBatchRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void PushBatchRequest::CopyFrom(const PushBatchRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:gwpush.PushBatchRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool PushBatchRequest::IsInitialized() const {
  return true;
}

void PushBatchRequest::Swap(PushBatchRequest* other) {
  if (other == this) return;
  InternalSwap(other);
}
void PushBatchRequest::InternalSwap(PushBatchRequest* other) {
  using std::swap;
  messages_.InternalSwap(&other->messages_);
  gateway_instance_id_.Swap(&other->gateway_instance_id_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata PushBatchRequest::GetMetadata() const {
  protobuf_gateway_5fpush_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_gateway_5fpush_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

void PushBatchResponse::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int PushBatchResponse::kOkFieldNumber;
const int PushBatchResponse::kMessageFieldNumber;
const int PushBatchResponse::kAcceptedFieldNumber;
const int PushBatchResponse::kRejectedFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

PushBatchResponse::PushBatchResponse()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    ::protobuf_gateway_5fpush_2eproto::InitDefaultsPushBatchResponse();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:gwpush.PushBatchResponse)
}
PushBatchResponse::PushBatchResponse(const PushBatchResponse& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  message_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.message().size() > 0) {
    message_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.message_);
  }
  ::memcpy(&ok_, &from.ok_,
    static_cast<size_t>(reinterpret_cast<char*>(&rejected_) -
    reinterpret_cast<char*>(&ok_)) + sizeof(rejected_));
  // @@protoc_insertion_point(copy_constructor:gwpush.PushBatchResponse)
}

void PushBatchResponse::SharedCtor() {
  message_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::memset(&ok_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&rejected_) -
      reinterpret_cast<char*>(&ok_)) + sizeof(rejected_));
  _cached_size_ = 0;
}

PushBatchResponse::~PushBatchResponse() {
  // @@protoc_insertion_point(destructor:gwpush.PushBatchResponse)
  SharedDtor();
}

void PushBatchResponse::SharedDtor() {
  message_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void PushBatchResponse::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* PushBatchResponse::descriptor() {
  ::protobuf_gateway_5fpush_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_gateway_5fpush_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const PushBatchResponse& PushBatchResponse::default_instance() {
  ::protobuf_gateway_5fpush_2eproto::InitDefaultsPushBatchResponse();
  return *internal_default_instance();
}

PushBatchResponse* PushBatchResponse::New(::google::protobuf::Arena* arena) const {
  PushBatchResponse* n = new PushBatchResponse;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void PushBatchResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:gwpush.PushBatchResponse)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  message_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::memset(&ok_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&rejected_) -
      reinterpret_cast<char*>(&ok_)) + sizeof(rejected_));
  _internal_metadata_.Clear();
}

bool PushBatchResponse::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:gwpush.PushBatchResponse)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // bool ok = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(8u /* 8 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 input, &ok_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string message = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(18u /* 18 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_message()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->message().data(), static_cast<int>(this->message().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "gwpush.PushBatchResponse.message"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // uint32 accepted = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(24u /* 24 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &accepted_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // uint32 rejected = 4;
      case 4: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(32u /* 32 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &rejected_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:gwpush.PushBatchResponse)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:gwpush.PushBatchResponse)
  return false;
#undef DO_
}

void PushBatchResponse::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:gwpush.PushBatchResponse)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // bool ok = 1;
  if (this->ok() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteBool(1, this->ok(), output);
  }

  // string message = 2;
  if (this->message().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->message().data(), static_cast<int>(this->message().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "gwpush.PushBatchResponse.message");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      2, this->message(), output);
  }

  // uint32 accepted = 3;
  if (this->accepted() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(3, this->accepted(), output);
  }

  // uint32 rejected = 4;
  if (this->rejected() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(4, this->rejected(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:gwpush.PushBatchResponse)
}

::google::protobuf::uint8* PushBatchResponse::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:gwpush.PushBatchResponse)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // bool ok = 1;
  if (this->ok() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteBoolToArray(1, this->ok(), target);
  }

  // string message = 2;
  if (this->message().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->message().data(), static_cast<int>(this->message().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "gwpush.PushBatchResponse.message");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        2, this->message(), target);
  }

  // uint32 accepted = 3;
  if (this->accepted() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(3, this->accepted(), target);
  }

  // uint32 rejected = 4;
  if (this->rejected() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(4, this->rejected(), target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:gwpush.PushBatchResponse)
  return target;
}

size_t PushBatchResponse::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:gwpush.PushBatchResponse)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // string message = 2;
  if (this->message().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->message());
  }

  // bool ok = 1;
  if (this->ok() != 0) {
    total_size += 1 + 1;
  }

  // uint32 accepted = 3;
  if (this->accepted() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt32Size(
        this->accepted());
  }

  // uint32 rejected = 4;
  if (this->rejected() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt32Size(
        this->rejected());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void PushBatchResponse::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:gwpush.PushBatchResponse)
  GOOGLE_DCHECK_NE(&from, this);
  const PushBatchResponse* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const PushBatchResponse>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:gwpush.PushBatchResponse)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:gwpush.PushBatchResponse)
    MergeFrom(*source);
  }
}

void PushBatchResponse::MergeFrom(const PushBatchResponse& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:gwpush.PushBatchResponse)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.message().size() > 0) {

    message_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.message_);
  }
  if (from.ok() != 0) {
    set_ok(from.ok());
  }
  if (from.accepted() != 0) {
    set_accepted(from.accepted());
  }
  if (from.rejected() != 0) {
    set_rejected(from.rejected());
  }
}

void PushBatchResponse::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:gwpush.PushBatchResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void PushBatchResponse::CopyFrom(const PushBatchResponse& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:gwpush.PushBatchResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool PushBatchResponse::IsInitialized() const {
  return true;
}

void PushBatchResponse::Swap(PushBatchResponse* other) {
  if (other == this) return;
  InternalSwap(other);
}
void PushBatchResponse::InternalSwap(PushBatchResponse* other) {
  using std::swap;
  message_.Swap(&other->message_);
  swap(ok_, other->ok_);
  swap(accepted_, other->accepted_);
  swap(rejected_, other->rejected_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata PushBatchResponse::GetMetadata() const {
  protobuf_gateway_5fpush_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_gateway_5fpush_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

GatewayPushService::~GatewayPushService() {}

const ::google::protobuf::ServiceDescriptor* GatewayPushService::descriptor() {
  protobuf_gateway_5fpush_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_gateway_5fpush_2eproto::file_level_service_descriptors[0];
}

const ::google::protobuf::ServiceDescriptor* GatewayPushService::GetDescriptor() {
  return descriptor();
}

void GatewayPushService::PushBatch(::google::protobuf::RpcController* controller,
                         const ::gwpush::PushBatchRequest*,
                         ::gwpush::PushBatchResponse*,
                         ::google::protobuf::Closure* done) {
  controller->SetFailed("Method PushBatch() not implemented.");
  done->Run();
}

void GatewayPushService::CallMethod(const ::google::protobuf::MethodDescriptor* method,
                             ::google::protobuf::RpcController* controller,
                             const ::google::protobuf::Message* request,
                             ::google::protobuf::Message* response,
                             ::google::protobuf::Closure* done) {
  GOOGLE_DCHECK_EQ(method->service(), protobuf_gateway_5fpush_2eproto::file_level_service_descriptors[0]);
  switch(method->index()) {
    case 0:
      PushBatch(controller,
             ::google::protobuf::down_cast<const ::gwpush::PushBatchRequest*>(request),
             ::google::protobuf::down_cast< ::gwpush::PushBatchResponse*>(response),
             done);
      break;
    default:
      GOOGLE_LOG(FATAL) << "Bad method index; this should never happen.";
      break;
  }
}

const ::google::protobuf::Message& GatewayPushService::GetRequestPrototype(
    const ::google::protobuf::MethodDescriptor* method) const {
  GOOGLE_DCHECK_EQ(method->service(), descriptor());
  switch(method->index()) {
    case 0:
      return ::gwpush::PushBatchRequest::default_instance();
    default:
      GOOGLE_LOG(FATAL) << "Bad method index; this should never happen.";
      return *::google::protobuf::MessageFactory::generated_factory()
          ->GetPrototype(method->input_type());
  }
}

const ::google::protobuf::Message& GatewayPushService::GetResponsePrototype(
    const ::google::protobuf::MethodDescriptor* method) const {
  GOOGLE_DCHECK_EQ(method->service(), descriptor());
  switch(method->index()) {
    case 0:
      return ::gwpush::PushBatchResponse::default_instance();
    default:
      GOOGLE_LOG(FATAL) << "Bad method index; this should never happen.";
      return *::google::protobuf::MessageFactory::generated_factory()
          ->GetPrototype(method->output_type());
  }
}

GatewayPushService_Stub::GatewayPushService_Stub(::google::protobuf::RpcChannel* channel)
  : channel_(channel), owns_channel_(false) {}
GatewayPushService_Stub::GatewayPushService_Stub(
    ::google::protobuf::RpcChannel* channel,
    ::google::protobuf::Service::ChannelOwnership ownership)
  : channel_(channel),
    owns_channel_(ownership == ::google::protobuf::Service::STUB_OWNS_CHANNEL) {}
GatewayPushService_Stub::~GatewayPushService_Stub() {
  if (owns_channel_) delete channel_;
}

void GatewayPushService_Stub::PushBatch(::google::protobuf::RpcController* controller,
                              const ::gwpush::PushBatchRequest* request,
                              ::gwpush::PushBatchResponse* response,
                              ::google::protobuf::Closure* done) {
  channel_->CallMethod(descriptor()->method(0),
                       controller, request, response, done);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace gwpush

// @@protoc_insertion_point(global_scope)
